%%% Copyright (C) 2018 Vincent Goulet
%%%
%%% Ce fichier fait partie du projet
%%% «Méthodes numériques en actuariat avec R»
%%% http://github.com/vigou3/methodes-numeriques-en-actuariat
%%%
%%% Cette création est mise à disposition selon le contrat
%%% Attribution-Partage dans les mêmes conditions 4.0
%%% International de Creative Commons.
%%% http://creativecommons.org/licenses/by-sa/4.0/

\chapter{Notions fondamentales d’algrèbre linéaire}
\label{chap:notions}

\begin{objectifs}
\item Utiliser les principaux opérateurs de l'arithmétique
  matricielle, dont la somme, le produit, la transposée et la trace.
\item Exprimer un système d'équations linéaires sous forme matricielle
  et le résoudre par élimination gaussienne ainsi que par produit de
  matrices élémentaires.
\item Vérifier si des éléments d'un espace vectoriel sont
  linéairement indépendants.
\item Définir les propriétés de l'inverse d'une matrice.
\item Définir les propriétés du déterminant d'une matrice.
\item Calculer l'inverse d'une matrice à partir de matrices
  élémentaires ainsi que par la méthode de la matrice adjointe.
\item Déterminer le rang d'une matrice.
\item Établir les liens entre les concepts ci-dessus.
\end{objectifs}

Ce chapitre propose une révision des éléments fondamentaux d'algèbre
linéaire normalement étudiés au collège: matrice, déterminant,
inverse, vecteur, espace vectoriel et relations avec les systèmes
d'équations linéaires. Nous tâchons d'insister sur l'établissement de
liens entre les différentes notions passées en revue. À ce titre, le
\autoref{thm:notions:unification} en fin de chapitre est
particulièrement important puisqu'il unifie un grand nombre de
résultats.

Le texte ne prétend à aucune exhaustivité; le lecteur devrait donc
consulter, au besoin, l'un des nombreux livres d'introduction à
l'algèbre linéaire disponibles en librairie ou à la bibliothèque. Les
éditions successives de \cite{Anton:linear:8e:2000} ont longtemps
servi pour les examens professionnels d'actuariat et constituent
toujours des références de choix.

Le langage R contient à peu près tous les outils nécessaires pour la
manipulation et le traitement des vecteurs et matrices; voir
\citet[chapitre~7]{Goulet:programmer-avec-r:2017}. Nous offrons une
révision dans le code informatique de la \autoref{sec:notions:code}.


\section{Matrices}
\label{sec:notions:matrices}

Une matrice est un tableau rectangulaire de nombres. Les matrices
seront généralement représentées par des lettres majuscules et leurs
éléments par des minuscules. Ainsi,
\begin{equation*}
  \mat{A} =
  \begin{bmatrix}
    a_{11} & a_{12} & \cdots & a_{1n} \\
    a_{21} & a_{22} & \cdots & a_{2n} \\
    \vdots & \vdots &      & \vdots \\
    a_{m1} & a_{m2} & \cdots & a_{mn}
  \end{bmatrix}
\end{equation*}
est une matrice $m \times n$ composée des éléments $a_{ij}$, $i = 1,
\dots, m$, $j = 1, \dots, n$. De manière plus compacte, on écrira parfois
\begin{align*}
  \mat{A} &= [a_{ij}]_{m \times n} \\
  \intertext{ou simplement}
  \mat{A} &= [a_{ij}]
\end{align*}
lorsque les dimensions de la matrices sont claires par le contexte.


\subsection{Matrice carrée}

Lorsqu'une matrice compte autant de lignes que de colonnes ($m = n$),
la matrice est dite \emph{carrée}. Dans un tel cas, les éléments
$a_{ii}$, $i = 1, \dots, n$ forment la \emph{diagonale} de la matrice.


\subsection{Matrice symétrique}

Si $a_{ij} = a_{ji}$ pour tout $i$, $j$, alors la matrice carrée
$\mat{A}$ est \emph{symétrique}. Par exemple,
\begin{equation*}
  \begin{bmatrix}
    2 & 3 & 4 & 5 \\
    3 & 1 & 0 & 6 \\
    4 & 0 & 2 & 7 \\
    5 & 6 & 7 & 1
  \end{bmatrix}
\end{equation*}
constitue une matrice symétrique.


\subsection{Matrices triangulaires et diagonales}

Une matrice carrée dont tous les éléments sous la diagonale sont nuls
est une matrice \emph{triangulaire supérieure}. À l'inverse, une
matrice carrée dont tous les éléments au-dessus de la diagonale sont
nuls est une matrice \emph{triangulaire inférieure}. Ainsi,
\begin{equation*}
  \begin{bmatrix}
    2 & 3 & 4 & 5 \\
    0 & 1 & 0 & 6 \\
    0 & 0 & 2 & 7 \\
    0 & 0 & 0 & 1
  \end{bmatrix}
\end{equation*}
est une matrice triangulaire supérieure, alors que
\begin{equation*}
  \begin{bmatrix}
    2 & 0 & 0 & 0 \\
    3 & 1 & 0 & 0 \\
    4 & 0 & 2 & 0 \\
    5 & 6 & 7 & 1
  \end{bmatrix}
\end{equation*}
est triangulaire inférieure.

Une matrice à la fois triangulaire inférieure et triangulaire
supérieure ne comporte que des zéros à l'extérieur de la diagonale et
est appelée une matrice \emph{diagonale}, comme par exemple
\begin{equation*}
  \begin{bmatrix}
    2 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 2 & 0 \\
    0 & 0 & 0 & 1
  \end{bmatrix}.
\end{equation*}


\subsection{Matrice identité et matrice zéro}

La matrice diagonale dont tous les éléments de la diagonale sont égaux
à 1 est appelée la \emph{matrice identité}.  Celle-ci joue un rôle
spécial important en algèbre matricielle. Elle est généralement notée
$\mat{I}$:
\begin{equation*}
  \mat{I}_{3 \times 3} =
  \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 \\
  \end{bmatrix}.
\end{equation*}

Finalement, la matrice constituée entièrement de 0 est appelée
\emph{matrice zéro} ou \emph{matrice nulle}. Elle est généralement notée
$\mat{0}$:
\begin{equation*}
  \mat{0}_{3 \times 3} =
  \begin{bmatrix}
    0 & 0 & 0 \\
    0 & 0 & 0 \\
    0 & 0 & 0 \\
  \end{bmatrix}.
\end{equation*}

La matrice nulle est tout-à-fait différente du scalaire 0.


\subsection{Vecteur ligne et vecteur colonne}

Les matrices comptant une seule ligne ou une seule colonne
portent un nom spécial. Une matrice $1 \times n$ est appelée
\emph{vecteur ligne} et une matrice $m \times 1$ est appelée
\emph{vecteur colonne} ou parfois simplement \emph{vecteur}. Ces deux
types de matrices sont généralement notées par des lettres minuscules
et leurs éléments sont numérotés par un seul indice:
\begin{equation*}
  \mat{a} =
  \begin{bmatrix}
    a_1 & a_2 & \cdots & a_n
  \end{bmatrix}, \quad
  \mat{b} =
  \begin{bmatrix}
    b_1 \\ b_2 \\ \vdots \\ b_m
  \end{bmatrix}.
\end{equation*}



\section{Arithmétique matricielle}
\label{sec:notions:arithmetique}

Cette section récapitule l'essentiel des règles d'arithmétique
matricielle. On gardera à l'esprit que ces règles sont parfois fort
différentes de celles de l'arithmétique des nombres, notamment au
chapitre du produit matriciel.


\subsection{Égalité, somme et différence}

Soit $\mat{A} = [a_{ij}]$ et $\mat{B} = [b_{ij}]$ deux matrices de
mêmes dimensions et $c$, une constante (scalaire). Alors,
\begin{enumerate}
\item $\mat{A} = \mat{B}$ si, et seulement si, $a_{ij} = b_{ij}$
  pour tout $i$ et tout $j$;
\item $\mat{A} + \mat{B} = [a_{ij} + b_{ij}]$;
\item $\mat{A} - \mat{B} = [a_{ij} - b_{ij}]$;
\item $c \mat{A} = [c a_{ij}]$.
\end{enumerate}


\subsection{Produit}

Le produit entre deux matrices, $\mat{AB}$, est défini seulement
si le nombre de colonnes de la matrice $\mat{A}$ est égal au nombre de
lignes de la matrice $\mat{B}$. Le résultat du produit est une matrice
dont l'élément en position $(i, j)$ correspond au produit scalaire
entre la ligne $i$ de la matrice $\mat{A}$ et la colonne $j$ de la
matrice $\mat{B}$. Autrement dit, soit $\mat{A}_{m \times p}$ et
$\mat{B}_{p \times n}$ deux matrices. Alors le produit $\mat{A}
\mat{B}$ est défini et
\begin{equation*}
  \mat{AB} = \left[ \sum_{k = 1}^p a_{ik} b_{kj} \right]_{m
    \times n}.
\end{equation*}

\begin{exemple}
  Soit les matrices
  \begin{equation*}
    \mat{A} =
    \begin{bmatrix}
      1 & 2 & 4 \\
      2 & 6 & 0
    \end{bmatrix}, \quad
    \mat{B} =
    \begin{bmatrix}[r]
      4 &  1 & 4 & 3 \\
      0 & -1 & 3 & 1 \\
      2 &  7 & 5 & 2
    \end{bmatrix}.
  \end{equation*}
  La matrice $\mat{A}$ compte trois colonnes, soit autant que le
  nombre de lignes de la matrice $\mat{B}$. Le produit $\mat{A}
  \mat{B}$ est donc défini. Le résultat sera une matrice $\mat{C}$ de
  deux lignes et quatre colonnes. On a
  \begin{align*}
    c_{11}
    &=
    \begin{bmatrix}
      1 & 2 & 4
    \end{bmatrix}
    \begin{bmatrix}
      4 \\ 0 \\ 2
    \end{bmatrix} \\
    &= (1 \cdot 4) + (2 \cdot 0) + (4 \cdot 2) \\
    &= 12, \displaybreak[0] \\
    c_{12}
    &=
    \begin{bmatrix}
      1 & 2 & 4
    \end{bmatrix}
    \begin{bmatrix}[r]
      1 \\ -1 \\ 7
    \end{bmatrix} \\
    &= (1 \cdot 1) + (2 \cdot -1) + (4 \cdot 7) \\
    &= 27,
  \end{align*}
  etc. Le résultat final est
  \begin{equation*}
    \mat{C} =
    \begin{bmatrix}[r]
      12 & 27 & 30 & 13 \\
       8 & -4 & 26 & 12
    \end{bmatrix}.
  \end{equation*}
  On remarquera que le produit $\mat{BA}$ n'est pas défini, ce qui
  illustre que le produit matriciel n'est pas commutatif.
  \qed
\end{exemple}

\begin{thm}[Propriétés de l'arithmétique matricielle]
  \label{thm:notions:arithmetique}
  Soit $\mat{A}$, $\mat{B}$ et $\mat{C}$ des matrices de dimensions
  telles que les opérations ci-dessous sont définies, et soit $a$ et
  $b$, des constantes.
  \begin{enumerate}
  \item $\mat{A} + \mat{B} = \mat{B} + \mat{A}$ (commutativité de l'addition)
  \item $\mat{A} + (\mat{B} + \mat{C}) = (\mat{A} + \mat{B}) + \mat{C}$
    (associativité de l'addition)
  \item $\mat{AB} \neq \mat{BA}$ en général
  \item $\mat{A(BC)} = \mat{(AB)C}$ (associativité de la multiplication)
  \item $\mat{A(B + C)} = \mat{AB} + \mat{AC}$ (distributivité par la gauche)
  \item $\mat{(B + C)A} = \mat{BA} + \mat{CA}$ (distributivité par la droite)
  \item $\mat{A(B - C)} = \mat{AB} - \mat{AC}$
  \item $\mat{(B - C)A} = \mat{BA} - \mat{CA}$
  \item $a(\mat{B} + \mat{C}) = a\mat{B} + a\mat{C}$
  \item $a(\mat{B} - \mat{C}) = a\mat{B} - a\mat{C}$
  \item $(a + b)\mat{C} = a\mat{C} + b\mat{C}$
  \item $(a - b)\mat{C} = a\mat{C} - b\mat{C}$
  \item $a(b\mat{C}) = (ab)\mat{C}$
  \item $a(\mat{BC}) = (a\mat{B})\mat{C} = \mat{B}(a\mat{C})$
  \end{enumerate}
\end{thm}

\begin{exemple}
  Soit $a = 5$, $b = 2$ et
  \begin{equation*}
    \mat{A} =
    \begin{bmatrix}
      1 & 2 \\
      3 & 4 \\
      0 & 1
    \end{bmatrix}, \quad
    \mat{B} =
    \begin{bmatrix}
      4 & 3 \\
      2 & 1
    \end{bmatrix}, \quad
    \mat{C} =
    \begin{bmatrix}
      1 & 0 \\
      2 & 3
    \end{bmatrix}.
  \end{equation*}
  Il est laissé en exercice de vérifier les propriétés du
  \autoref{thm:notions:arithmetique}. On remarquera que $\mat{AB}$
  est défini, mais pas $\mat{BA}$, ce qui vérifie la propriété 3, mais
  empêche de faire les opérations des propriétés 6 et 8. On remarquera
  de plus que $\mat{BC} \neq \mat{CB}$. \qed
\end{exemple}


\subsection{Rôles la matrice identité et de la matrice zéro}

La matrice identité joue, en arithmétique matricielle,  le rôle du
nombre $1$ en arithmétique usuelle. Ainsi,
\begin{equation*}
  \mat{A}_{m \times n} \mat{I}_n = \mat{I}_m \mat{A}_{m \times n} = \mat{A}.
\end{equation*}

De même, la matrice zéro joue un rôle similaire à celui du $0$ en
arithmétique.
\begin{thm}[Propriétés de la matrice zéro]
  \label{thm:notions:zero}
  En supposant que les matrices sont de dimensions appropriées pour
  que les opérations soient définies, les propriétés ci-dessous sont
  valides en arithmétique matricielle.
  \begin{enumerate}
  \item $\mat{A} + \mat{0} = \mat{0} + \mat{A} = \mat{A}$
  \item $\mat{A} - \mat{A} = \mat{0}$
  \item $\mat{0} - \mat{A} = - \mat{A}$
  \item $\mat{A0} = \mat{0}$ et $\mat{0A} = \mat{0}$
  \end{enumerate}
\end{thm}

L'exemple suivant illustre toutefois les limites aux similitudes entre
les deux systèmes arithmétiques.

\begin{exemple}
  Soit les matrices
  \begin{equation*}
    \mat{A} =
    \begin{bmatrix}
      0 & 1 \\
      0 & 2
    \end{bmatrix}, \quad
    \mat{B} =
    \begin{bmatrix}
      1 & 1 \\
      3 & 4
    \end{bmatrix}, \quad
    \mat{C} =
    \begin{bmatrix}
      2 & 5 \\
      3 & 4
    \end{bmatrix}, \quad
    \mat{D} =
    \begin{bmatrix}
      3 & 7 \\
      0 & 0
    \end{bmatrix}.
  \end{equation*}
  On vérifie aisément que
  \begin{equation*}
    \mat{AB} = \mat{AC} =
    \begin{bmatrix}
      3 & 4 \\
      6 & 8
    \end{bmatrix},
  \end{equation*}
  d'où $\mat{AB} = \mat{AC}$ n'implique pas nécessairement $\mat{B} =
  \mat{C}$. De même, on vérifie que $\mat{AD} = \mat{0}$ même si
  $\mat{A} \neq \mat{0}$ et $\mat{D} \neq \mat{0}$.
  \qed
\end{exemple}


\subsection{Trace}

La \emph{trace} d'une matrice carrée $\mat{A}_{n \times n}$, notée
$\tr(\mat{A})$, est égale à la somme des éléments de la
diagonale:
\begin{equation*}
  \tr(\mat{A}) = \sum_{i = 1}^n a_{ii}.
\end{equation*}


\subsection{Transposée}

La \emph{transposée} d'une matrice $\mat{A}$ est la matrice obtenue en
échangeant les lignes et les colonnes de $\mat{A}$. Elle est
généralement notée $\mat{A}^T$ ou $\mat{A}^\prime$:
\begin{equation*}
  \mat{A} = [a_{ij}] \Rightarrow \mat{A}^T = [a_{ji}].
\end{equation*}

\begin{thm}[Propriétés de la transposée]
  \label{thm:notions:transposee}
  Soit $\mat{A}$, $\mat{B}$ et $\mat{C}$ des matrices de dimensions
  telles que les opérations ci-dessous sont définies, et soit $k$ une
  constante.
  \begin{enumerate}
  \item $(\mat{A}^T)^T = \mat{A}$
  \item $(\mat{A} + \mat{B})^T = \mat{A}^T + \mat{B}^T$
  \item $(k \mat{A})^T = k \mat{A}^T$
  \item $(\mat{AB})^T = \mat{B}^T \mat{A}^T$
  \item $\mat{A}^T \mat{A}$ et $\mat{A} \mat{A}^T$ sont symétriques.
  \end{enumerate}
\end{thm}
\begin{proof}
  On ne démontre que les propriétés 4 et 5. En premier lieu, soit
  $\mat{A}_{m \times p}$ et $\mat{B}_{p \times m}$ des matrices,
  $\mat{C} = (\mat{A} \mat{B})^T$ et $\mat{D} = \mat{B}_{m \times p}^T
  \mat{A}_{p \times m}^T$. L'élément $c_{ij}$ de la matrice $\mat{C}$
  est égal à l'élément en position $(j, i)$ du produit $\mat{AB}$,
  d'où
  \begin{equation*}
    c_{ij} = \sum_{k = 1}^p a_{jk} b_{ki}.
  \end{equation*}
  De plus, puisque $\mat{A}^T = [a_{ji}]$ et $\mat{B}^T = [b_{ji}]$
  \begin{equation*}
    d_{ij} = \sum_{k = 1}^p b_{ki} a_{jk},
  \end{equation*}
  d'où $c_{ij} = d_{ij}$ pour tout $i = 1, \dots, m$ et $j = 1, \dots,
  m$ et, donc, $\mat{C} = \mat{D}$.

  D'autre part, par la propriété 4,
  \begin{align*}
    (\mat{A}^T \mat{A})^T
    &= \mat{A}^T (\mat{A}^T)^T \\
    &= \mat{A}^T \mat{A},
  \end{align*}
  d'où $\mat{A}^T \mat{A}$ est une matrice symétrique. On procède de
  même pour le second résultat de la propriété 5.
\end{proof}


\section{Lien avec les systèmes d'équations linéaires}
\label{sec:notions:syseq}

L'application de loin la plus fréquente des matrices est la
représentation et la résolution de systèmes d'équations linéaires.
Soit le système à trois équations et trois inconnues
\begin{align*}
  a_{11} x_1 + a_{12} x_2 + a_{13} x_3 &= b_1 \\
  a_{21} x_1 + a_{22} x_2 + a_{23} x_3 &= b_2 \\
  a_{31} x_1 + a_{32} x_2 + a_{33} x_3 &= b_3.
\end{align*}
On peut représenter ce système sous la forme d'une équation
matricielle avec
\begin{gather*}
  \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33}
  \end{bmatrix}
  \begin{bmatrix}
    x_1 \\ x_2 \\ x_3
  \end{bmatrix} =
  \begin{bmatrix}
    b_1 \\ b_2 \\ b_3
  \end{bmatrix}, \\
  \intertext{soit}
  \mat{A x} = \mat{b},
\end{gather*}
avec les définitions évidentes pour $\mat{A}$, $\mat{x}$ et $\mat{b}$.

Tout système d'équations linéaires comporte ou bien une seule
solution, ou bien aucune solution, ou bien une infinité de solutions.
La \autoref{fig:notions:solutions} illustre ces trois possibilités
pour un système à deux équations et deux inconnues, de même que pour
un système à trois équations et trois inconnues.

\begin{rem}
  Un système avec plus d'inconnues qu'il n'y a d'équations ($m < n$)
  ne peut avoir qu'aucune ou une infinité de solutions. (Il est, par
  exemple, impossible d'avoir un seul point commun entre deux plans.)
\end{rem}

\SweaveOpts{width=3,height=3}

\begin{figure}[t]
  \centering
  (a) \quad
  \begin{minipage}[c]{0.4\linewidth}
<<echo=FALSE, fig=TRUE, width=5, height=3>>=
par(mar = c(2, 2, 1, 1))
f <- function(x) 2 * x + 2
g <- function(x) -3 * x + 12
curve(f, xlim = c(0, 5), xlab = "", ylab = "", col = "blue", lwd = 4)
curve(g, xlim = c(0, 5), add = TRUE, col = "red", lwd = 4)
points(2, 6, pch = 19, cex = 1.5)
@
  \end{minipage}
  \begin{minipage}[c]{0.4\linewidth}
    \scalebox{1.5}{\includegraphics{unique_3d}}
  \end{minipage}
  \newline
  (b) \quad
  \begin{minipage}[c]{0.4\linewidth}
<<echo=FALSE, fig=TRUE, width=5, height=3>>=
par(mar = c(2, 2, 1, 1))
f <- function(x) 2 * x + 2
g <- function(x) 2 * x + 4
curve(f, xlim = c(0, 5), xlab = "", ylab = "", col = "blue", lwd = 4)
curve(g, xlim = c(0, 5), add = TRUE, col = "red", lwd = 4)
@
  \end{minipage}
  \begin{minipage}[c]{0.4\linewidth}
    \scalebox{1.5}{\includegraphics{aucune_3d}}
  \end{minipage}
  \newline
  (c) \quad
  \begin{minipage}[c]{0.4\linewidth}
<<echo=FALSE, fig=TRUE, width=5, height=3>>=
par(mar = c(2, 2, 1, 1))
f <- function(x) 2 * x + 2
g <- function(x) 2 * x + 2.07
curve(f, xlim = c(0, 5), xlab = "", ylab = "", col = "blue", lwd = 4)
curve(g, xlim = c(0, 5), add = TRUE, col = "red", lwd = 4)
@
  \footnotesize\hspace*{1em}%
  (droites superposées)
  \end{minipage}
  \begin{minipage}[c]{0.4\linewidth}
    \scalebox{1.5}{\includegraphics{infinite_3d}}
  \end{minipage}
  \newline
  \caption{Solutions possibles de systèmes d'équations linéaires à
    deux et trois variables: (a) une seule solution; (b) aucune
    solution; (c) infinité de solutions. La ou les solutions sont
    illustrées par un point ou une droite en noir, lorsque possible.}
  \label{fig:notions:solutions}
\end{figure}


\subsection{Résolution d'un système d'équations linéaires}

De manière plus compacte et appropriée pour l'élimination gaussienne
(voir plus bas), le système d'équation $\mat{Ax} = \mat{b}$ peut aussi
être représenté sous forme d'une \emph{matrice augmentée}
\begin{equation*}
  \begin{bmatrix}
    a_{11} & a_{12} & a_{13} & b_1 \\
    a_{21} & a_{22} & a_{23} & b_2 \\
    a_{31} & a_{32} & a_{33} & b_3
  \end{bmatrix}.
\end{equation*}

Pour résoudre un système d'équations linéaires, on remplace
généralement le système donné par un autre système équivalent, mais
plus simple à résoudre. Ce nouveau système est obtenu par diverses
opérations:
\begin{enumerate}
\item multiplication d'une équation par une constante;
\item échange de deux équations;
\item addition d'un multiple d'une équation à une autre.
\end{enumerate}

Puisque les lignes d'une matrice augmentée correspondent aux équations
d'un système d'équations, les opérations ci-dessus se traduisent
naturellement en opérations sur les lignes de la matrice augmentée:
\begin{enumerate}
\item multiplication d'une ligne par une constante;
\item échange de deux lignes;
\item addition d'un multiple d'une ligne à une autre.
\end{enumerate}
Ces opérations sont appelées \emph{opérations élémentaires sur les lignes}.

\begin{exemple}
  \label{ex:notions:gaussienne}
  Soit le système d'équations
  \begin{align*}
     x +  y + 2z &= 9 \\
    2x + 4y - 3z &= 1 \\
    3x + 6y - 5z &= 0.
  \end{align*}
  La procédure de résolution classique du système d'équations se
  trouve dans la colonne de gauche, alors que la procédure utilisant
  la matrice augmentée se trouve dans la colonne de droite.
  \begin{adjustwidth}{\parindent}{\parindent}
    \begin{minipage}[t]{0.48\linewidth}
      Système d'équations original:
      \begin{align*}
        x +  y + 2z &= 9 \\
        2x + 4y - 3z &= 1 \\
        3x + 6y - 5z &= 0.
      \end{align*}
    \end{minipage}
    \hfill
    \begin{minipage}[t]{0.48\linewidth}
      Matrice augmentée originale:
      \begin{align*}
        \begin{bmatrix}
          1 & 1 &  2 & 9 \\
          2 & 4 & -3 & 1 \\
          3 & 6 & -5 & 0
        \end{bmatrix}
      \end{align*}
    \end{minipage} \\[12pt]
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-2$ fois la première équation à la seconde et $-3$
      fois la première à la troisième:
      \begin{align*}
        x +  y +  2z &=   9 \\
            2y -  7z &= -17 \\
            3y - 11z &= -27.
      \end{align*}
    \end{minipage}
    \hfill
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-2$ fois la première ligne à la seconde et $-3$
      fois la première à la troisième:
      \begin{align*}
        \begin{bmatrix}
          1 & 1 &   2 & 9 \\
          0 & 2 &  -7 & -17 \\
          0 & 3 & -11 & -27
        \end{bmatrix}
      \end{align*}
    \end{minipage} \\[12pt]
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-\frac{3}{2}$ fois la seconde équation à la
      troisième:
      \begin{align*}
        x +  y +  2z &=   9 \\
            2y -  7z &= -17 \\
      - \frac{1}{2}z &= -\frac{3}{2}.
      \end{align*}
    \end{minipage}
    \hfill
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-\frac{3}{2}$ fois la seconde ligne à la troisième:
      \begin{align*}
        \begin{bmatrix}
          1 & 1 &   2 & 9 \\
          0 & 2 &  -7 & -17 \\
          0 & 0 & -\frac{1}{2} & -\frac{3}{2}
        \end{bmatrix}
      \end{align*}
    \end{minipage} \\[12pt]
  \end{adjustwidth}

  À cette étape on peut déjà résoudre facilement le système
  d'équations par substitution successive: la troisième équation nous
  donne $z = 3$, la seconde $2y - 7(3) = -17 \Rightarrow y = 2$ et la
  première, $x + 2 + 2(3) = 9 \Rightarrow x = 1$.

  On peut aussi continuer les opérations élémentaires jusqu'à obtenir
  un système trivial.

  \begin{adjustwidth}{\parindent}{\parindent}
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-14$ fois la troisième équation à la seconde et $4$
      fois la troisième à la première:
      \begin{align*}
        x +  y  &=  3 \\
             2y &= 4 \\
          -\frac{1}{2}z &= -\frac{3}{2}.
      \end{align*}
    \end{minipage}
    \hfill
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-14$ fois la troisième ligne à la seconde et $4$
      fois la troisième à la première:
      \begin{align*}
        \begin{bmatrix}
          1 & 1 &  0 & 3 \\
          0 & 2 &  0 & 4 \\
          0 & 0 & -\frac{1}{2} & -\frac{3}{2}
        \end{bmatrix}
      \end{align*}
    \end{minipage} \\[12pt]
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-\frac{1}{2}$ fois la seconde équation à la première:
      \begin{align*}
        x &=  1 \\
       2y &= 4 \\
       -\frac{1}{2}z &= -\frac{3}{2}.
      \end{align*}
    \end{minipage}
    \hfill
    \begin{minipage}[t]{0.48\linewidth}
      Additionner $-\frac{1}{2}$ fois la seconde ligne à la première:
      \begin{align*}
        \begin{bmatrix}
          1 & 0 &  0 & 1 \\
          0 & 2 &  0 & 4 \\
          0 & 0 & -\frac{1}{2} & -\frac{3}{2}
        \end{bmatrix}
      \end{align*}
    \end{minipage}
  \end{adjustwidth}
  On obtient la même réponse que ci-dessus avec ce dernier système
  d'équations.
  \qed
\end{exemple}


\subsection{Élimination gaussienne}

La procédure de la matrice augmentée utilisée pour résoudre le système
d'équations de l'\autoref{ex:notions:gaussienne} s'apparente à
l'\emph{élimination gaussienne}. Plus précisément, l'élimination
gaussienne consiste à appliquer des opérations élémentaires à la
matrice augmentée correspondant à un système d'équations linéaires
jusqu'à ce que la partie gauche de celle-ci se trouve sous forme
\emph{échelonnée}, c'est-à-dire:
\begin{enumerate}
\item si une ligne n'est pas constituée uniquement de zéros, alors le
  premier élément non nul de cette ligne est un 1;
\item les lignes composées uniquement de zéros sont groupées au bas de
  la matrice;
\item pour toutes les lignes adjacentes non composées uniquement de
  zéros, le premier 1 suivant des zéros apparaît plus à droite dans la
  ligne du dessous.
\end{enumerate}

\begin{exemple}
  Les matrices suivantes sont échelonnées (le symbole $*$ représente
  un nombre quelconque):
  \begin{gather*}
    \begin{bmatrix}
      1 & * & * & * \\
      0 & 1 & * & * \\
      0 & 0 & 1 & * \\
      0 & 0 & 0 & 1
    \end{bmatrix}, \;
    \begin{bmatrix}
      1 & * & * & * \\
      0 & 1 & * & * \\
      0 & 0 & 1 & * \\
      0 & 0 & 0 & 0
    \end{bmatrix}, \;
    \begin{bmatrix}
      1 & * & * & * \\
      0 & 1 & * & * \\
      0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0
    \end{bmatrix}, \;
    \begin{bmatrix}
      1 & * & * & * & * \\
      0 & 1 & * & * & * \\
      0 & 0 & 0 & 1 & * \\
      0 & 0 & 0 & 0 & 0
    \end{bmatrix}.
  \end{gather*}
  \qed
\end{exemple}

Si on ajoute l'exigence que le premier 1 suivant des zéros d'une
colonne ne soit lui-même suivi que de zéros, alors la matrice est
résultante est sous forme \emph{échelonnée réduite}. La procédure de
résolution du système d'équations linéaires est alors appelée
\emph{élimination de Gauss--Jordan}.

\begin{exemple}
  Les matrices suivantes sont sous forme échelonnée réduite:
  \begin{gather*}
    \begin{bmatrix}
      1 & 0 & 0 & 0 \\
      0 & 1 & 0 & 0 \\
      0 & 0 & 1 & 0 \\
      0 & 0 & 0 & 1
    \end{bmatrix}, \;
    \begin{bmatrix}
      1 & 0 & 0 & * \\
      0 & 1 & 0 & * \\
      0 & 0 & 1 & * \\
      0 & 0 & 0 & 0
    \end{bmatrix}, \;
    \begin{bmatrix}
      1 & 0 & * & * \\
      0 & 1 & * & * \\
      0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0
    \end{bmatrix}, \;
    \begin{bmatrix}
      1 & 0 & * & 0 & * \\
      0 & 1 & * & 0 & * \\
      0 & 0 & 0 & 1 & * \\
      0 & 0 & 0 & 0 & 0
    \end{bmatrix}.
  \end{gather*}
  \qed
\end{exemple}

\begin{exemple}
  La matrice échelonnée réduite d'un système d'équations linéaires est
  la suivante:
  \begin{equation*}
    \begin{bmatrix}
      1 & 0 & 0 & 4 & -1 \\
      0 & 1 & 0 & 2 &  6 \\
      0 & 0 & 1 & 3 &  2
    \end{bmatrix}.
  \end{equation*}
  Le système d'équations compte plus d'inconnues que d'équations. On
  sait donc qu'il aura une infinité de solutions. Le système
  correspondant à la matrice échelonnée réduite est
  \begin{align*}
    x_1 + 4 x_4 &= -1 \\
    x_2 + 2 x_4 &= 6 \\
    x_3 + 3 x_4 &= 2,
  \end{align*}
  soit
  \begin{align*}
    x_1 &= -1 - 4 x_4 \\
    x_2 &= 6 - 2 x_4 \\
    x_3 &= 2 - 3 x_4.
  \end{align*}
  Afin d'exprimer l'ensemble de solutions, on a recours à une (ou
  plusieurs, le cas échéant) \emph{variable libre} égale à une valeur
  quelconque. Ici, on choisira tout naturellement de poser $x_4 =
  t$. Ainsi, on a la solution générale
  \begin{align*}
    x_1 &= -1 - 4 t, &
    x_2 &= 6 - 2 t, &
    x_3 &= 2 - 3 t, &
    x_4 &= t.
  \end{align*}
  \qed
\end{exemple}

L'élimination gaussienne et l'élimination de Gauss--Jordan se prêtent
bien à la mise en oeuvre informatique de méthodes de résolution de
grands systèmes d'équations linéaires. Un algorithme efficace prendra
toutefois soin de minimiser les erreurs d'arrondi ainsi que le nombre
d'opérations. Nous étudierons au \autoref{chap:decomposition} la
méthode la plus souvent retenue pour résoudre les systèmes d'équations
linéaires.


\subsection{Matrices élémentaires}

Les opérations élémentaires réalisées sur une matrice peuvent être
représentées comme un produit entre une \emph{matrice élémentaire} et
la matrice (dans cet ordre). Une matrice élémentaire $n \times n$ est
le résultat d'une --- et une seule --- opération sur les lignes de la
matrice identité $\mat{I}_n$.

Par exemple, soit la matrice
\begin{equation*}
  \mat{A} =
  \begin{bmatrix}
    1 & 2 \\
    3 & 4
  \end{bmatrix}.
\end{equation*}
Pour intervertir les deux lignes de $\mat{A}$, on peut faire le
produit
\begin{equation*}
  \begin{bmatrix}
    0 & 1 \\
    1 & 0
  \end{bmatrix}
  \begin{bmatrix}
    1 & 2 \\
    3 & 4
  \end{bmatrix} =
  \begin{bmatrix}
    3 & 4 \\
    1 & 2
  \end{bmatrix}.
\end{equation*}
Pour additionner à la première ligne $2$ fois la seconde, on peut faire
le produit
\begin{equation*}
  \begin{bmatrix}
    1 & 2 \\
    0 & 1
  \end{bmatrix}
  \begin{bmatrix}
    1 & 2 \\
    3 & 4
  \end{bmatrix} =
  \begin{bmatrix}
    7 & 10 \\
    3 & 4
  \end{bmatrix}.
\end{equation*}
Les matrices les plus à gauche dans les produits ci-dessus sont des
matrices élémentaires.

Les matrices élémentaires sont généralement notées $\mat{E}$. Leur
principale propriété est formalisée dans le théorème suivant.

\begin{thm}
  Soit $\mat{E}$ une matrice obtenue en faisant une opération sur les
  lignes de la matrice identité. Alors $\mat{E} \mat{A}$ est la
  matrice obtenue en faisant la même opération sur la matrice
  $\mat{A}$.
\end{thm}

\begin{exemple}
  On exprime la solution de l'\autoref{ex:notions:gaussienne} à
  l'aide de matrices élémentaires. À chaque opération sur les lignes
  de la matrice augmentée correspond une matrice élémentaire.
  \begin{enumerate}
  \item Additionner $-2$ fois la première ligne à la seconde:
    \begin{equation*}
      \mat{E}_1 =
      \begin{bmatrix}
        1 & 0 & 0 \\
        -2 & 1 & 0 \\
        0 & 0 & 1
      \end{bmatrix}.
    \end{equation*}
  \item Additionner $-3$ fois la première ligne à la troisième:
    \begin{equation*}
      \mat{E}_2 =
      \begin{bmatrix}
        1 & 0 & 0 \\
        0 & 1 & 0 \\
        -3 & 0 & 1
      \end{bmatrix}.
    \end{equation*}
  \item Additionner $-\frac{3}{2}$ fois la seconde ligne à la
    troisième:
    \begin{equation*}
      \mat{E}_3 =
      \begin{bmatrix}
        1 & 0 & 0 \\
        0 & 1 & 0 \\
        0 & -\frac{3}{2} & 1
      \end{bmatrix}.
    \end{equation*}
  \end{enumerate}
  Il est laissé en exercice de vérifier que
  \begin{equation*}
    \mat{E}_3 \mat{E}_2 \mat{E}_1
    \begin{bmatrix}
      1 & 1 &  2 & 9 \\
      2 & 4 & -3 & 1 \\
      3 & 6 & -5 & 0
    \end{bmatrix} =
    \begin{bmatrix}
      1 & 1 &   2 & 9 \\
      0 & 2 &  -7 & -17 \\
      0 & 0 & -\frac{1}{2} & -\frac{3}{2}
    \end{bmatrix}.
  \end{equation*}
  \qed
\end{exemple}

Les matrices élémentaires seront utiles lorsque nous étudierons la
décomposition $LU$ au \autoref{chap:decomposition}.


\subsection{Systèmes d'équations homogènes}

Un système d'équations linéaires est dit \emph{homogène} lorsque
$\mat{b} = \mat{0}$, c'est-à-dire de la forme
\begin{align*}
  a_{11} x_1 + \dots + a_{1n} x_n &= 0 \\
  a_{21} x_1 + \dots + a_{2n} x_n &= 0 \\
  &\;\;\vdots \\
  a_{m1} x_1 + \dots + a_{mn} x_n &= 0.
\end{align*}
Tout système d'équations homogène compte au moins une solution, la
\emph{solution triviale} $x_1 = \dots = x_n = 0$. Par conséquent, de
tels systèmes peuvent n'admettre que la solution triviale ou une
infinité de solutions.

\begin{thm}
  Tout système d'équations homogène composé de plus d'inconnues que
  d'équations $(m < n)$ a une infinité de solutions.
\end{thm}



\section{Lien avec les espaces vectoriels}
\label{sec:notions:vecteurs}

L'algèbre vectorielle sera peu étudiée dans ce cours, mais il est
néanmoins utile de mentionner brièvement la relation entre les
matrices et les espaces vectoriels.

De manière très générale, un \emph{espace vectoriel} est un ensemble
d'objets pour lequel sont définis un opérateur d'addition et un
opérateur de produit par un scalaire, tous deux satisfaisant un
certain nombre de conditions.

\begin{definition}[Espace vectoriel]
  Soit $V$ un ensemble non vide d'objets. Si les axiomes ci-dessous
  sont satisfaits pour tous objets $\mat{u}$, $\mat{v}$ et $\mat{w}$
  de $V$ et tous scalaires $k$ et $l$, alors $V$ est un espace
  vectoriel.
  \begin{enumerate}
  \item Si $\mat{u} \in V$ et $\mat{v} \in V$, alors $\mat{u} +
    \mat{v} \in V$.
  \item $\mat{u} + \mat{v} = \mat{v} + \mat{u}$
  \item $\mat{u} + (\mat{v} + \mat{w}) = (\mat{u} + \mat{v}) + \mat{w}$
  \item Il existe un objet $\mat{0} \in V$ tel que $\mat{u} + \mat{0}
    = \mat{0} + \mat{u} = \mat{u}$ pour tout $\mat{u} \in V$.
  \item Pour tout $\mat{u} \in V$, il existe un objet $-\mat{u}$ tel
    que $\mat{u} + (-\mat{u}) = (-\mat{u}) + \mat{u} = \mat{0}$.
  \item Si $k$ est un scalaire et $\mat{u} \in V$, alors $k \mat{u}
    \in V$.
  \item $k(\mat{u} + \mat{v}) = k \mat{u} + k \mat{v}$
  \item $(k + l) \mat{u} = k \mat{u} + l \mat{u}$
  \item $k (l \mat{u}) = (kl) \mat{u}$
  \item $1 \mat{u} = \mat{u}$
  \end{enumerate}
\end{definition}

\begin{definition}[Produit scalaire]
  Soit $\mat{u}$, $\mat{v}$ et $\mat{w}$ des éléments d'un espace
  vectoriel $V$ et $k$, un scalaire. Un produit scalaire dans $V$ est
  une fonction $\pscal{\mat{u}}{\mat{v}}$ associant un nombre réel aux
  éléments $\mat{u}$ et $\mat{v}$ de $V$ et respectant les axiomes
  suivants:
  \begin{enumerate}
  \item $\pscal{\mat{u}}{\mat{v}} = \pscal{\mat{v}}{\mat{u}}$
    (symétrie)
  \item $\pscal{\mat{u} + \mat{v}}{\mat{w}} = \pscal{\mat{u}}{\mat{w}}
    + \pscal{\mat{v}}{\mat{w}}$ (distributivité)
  \item $\pscal{k \mat{u}}{\mat{v}} = k \pscal{\mat{u}}{\mat{v}}$
  \item $\pscal{\mat{v}}{\mat{v}} \geq 0$ et $\pscal{\mat{v}}{\mat{v}}
    = 0$ si, et seulement si, $\mat{v} = 0$.
  \end{enumerate}
\end{definition}

\begin{definition}[Norme]
  La norme (longueur) d'un vecteur $\mat{u}$, notée $\| \mat{u} \|$,
  est la racine carrée du produit scalaire du vecteur avec lui-même:
  \begin{equation*}
    \| \mat{u} \| = \sqrt{\pscal{\mat{u}}{\mat{u}}}.
  \end{equation*}
\end{definition}

\begin{definition}[Espace pré-hilbertien]
  Un espace pré-hilbertien (\emph{inner product space}) est un espace
  vectoriel muni d'un produit scalaire.
\end{definition}

\begin{definition}[Orthogonalité]
  Deux éléments $\mat{u}$ et $\mat{v}$ d'un espace pré-hil\-ber\-tien sont
  orthogonaux si $\pscal{\mat{u}}{\mat{v}} = 0$.
\end{definition}

\begin{exemple}
  L'espace euclidien $\R^n$ est un espace pré-hilbertien pour
  lequel l'addition et le produit par un scalaire sont respectivement
  définis par
  \begin{align*}
    \mat{u} + \mat{v} &= [u_i + v_i] \\
    \intertext{et}
    k \mat{v} &= [k v_i],
  \end{align*}
  où $\mat{u} = (u_1, \dots, u_n)$ et $\mat{v} = (v_1, \dots, v_n)$
  sont deux vecteurs et $k$ est une constante. De plus, le produit
  scalaire dans $\R^n$ est défini ainsi:
  \begin{equation*}
    \pscal{\mat{u}}{\mat{v}} = \mat{u}^T \mat{v} = \sum_{i = 1}^n u_i v_i.
  \end{equation*}
  Par conséquent, la norme d'un vecteur dans $\R^n$ est la
  racine carrée de la somme des composantes au carré ou, si l'on préfère:
  \begin{equation*}
    \| \mat{u} \|^2 = \sum_{i = 1}^n u_i^2.
  \end{equation*}
  \qed
\end{exemple}

\begin{exemple}
  L'ensemble des variables aléatoires de second moment fini forme un
  espace pré-hilbertien communément noté $\mathcal{L}^2$. En effet,
  tant la somme $X + Y$ de deux variables aléatoires de second moment
  fini que le produit d'une variable aléatoire par une constante $k X$
  sont des variables aléatoires de second moment fini. De plus, le
  produit scalaire est défini ainsi dans cet espace:
  \begin{equation*}
    \pscal{X}{Y} = \esp{XY}.
  \end{equation*}
  La notion d'orthogonalité est donc liée à celle d'indépendance
  stochastique dans cet espace. %
  \qed
\end{exemple}

On peut voir la matrice
\begin{equation*}
  \mat{A} =
  \begin{bmatrix}
    a_{11} & a_{12} & \cdots & a_{1m} \\
    a_{21} & a_{22} & \cdots & a_{2m} \\
    \vdots & \vdots &      & \vdots \\
    a_{n1} & a_{n2} & \cdots & a_{nm}
  \end{bmatrix}
\end{equation*}
comme la réunion dans un même objet des coordonnées (dans un espace à
$n$ dimensions) de $m$ vecteurs $\mat{a}_1, \dots, \mat{a}_m$:
\begin{equation*}
  \mat{A} =
  \begin{bmatrix}
    \mat{a}_1 & \mat{a}_2 & \cdots & \mat{a}_m
  \end{bmatrix},
\end{equation*}
où $\mat{a}_i = (a_{1i}, \dots, a_{ni})$. Les règles de l'arithmétique
matricielle nous fournissent donc une arithmétique pour les espaces
vectoriels.

La principale notion d'algèbre vectorielle qui nous sera utile ici est
celle d'indépendance linéaire.

Soit $V = \{\mat{v}_1, \dots, \mat{v}_n\}$ un ensemble de vecteurs non
nuls. Si la seule solution de l'équation vectorielle
\begin{equation*}
  k_1 \mat{v}_1 + \dots + k_n \mat{v}_n = \mat{0}
\end{equation*}
est la solution triviale $k_1 = 0, \dots, k_n = 0$, alors $V$ est un
ensemble \emph{linéairement indépendant}. S'il existe une autre
solution que la solution triviale à l'équation, alors $V$ est un
ensemble \emph{linéairement dépendant}.

Lorsque $V = \{\mat{v}_1, \dots, \mat{v}_n\}$ est un ensemble de
vecteurs linéairement indépendants, on dit que $V$ forme une
\emph{base} pour l'espace vectoriel.

\begin{exemple}
  Soit $\mat{v}_1 = (2, -1, 0, 3)$, $\mat{v}_2 = (1, 2, 5, -1)$ et
  $\mat{v}_3 = (7, -1, 5, 8)$. Ces trois vecteurs sont linéairement
  dépendants puisque $3 \mat{v}_1 + \mat{v}_2 - \mat{v}_3 = \mat{0}$.
  Ils ne peuvent donc pas servir de base pour $\R^4$.
  \qed
\end{exemple}

\begin{exemple}
  Les vecteurs $\mat{i} = (1, 0, 0)$, $\mat{j} = (0, 1, 0)$ et
  $\mat{k} = (0, 0, 1)$ sont linéairement indépendants puisque
  \begin{align*}
    k_1 \mat{i} + k_2 \mat{j} + k_3 \mat{k}
    &= (k_1, 0, 0) + (0, k_2, 0) + (0, 0, k_3) \\
    &= (k_1, k_2, k_3) \\
    &= (0, 0, 0)
  \end{align*}
  seulement si $k_1 = k_2 = k_3 = 0$. Ces vecteurs forment une base
  pour l'espace $\R^3$.
  \qed
\end{exemple}

Pour établir le lien entre l'indépendance linéaire et les matrices,
supposons un ensemble de trois vecteurs $V = \{\mat{v}_1, \mat{v}_2,
\mat{v}_3\}$, où $\mat{v}_i = (v_{1i}, v_{2i}, v_{3i})$. Les vecteurs
sont linéairement indépendants si
\begin{equation*}
  k_1 \mat{v}_1 + k_2 \mat{v}_2 + k_3 \mat{v}_3 = \mat{0},
\end{equation*}
soit
\begin{equation*}
  k_1 (v_{11}, v_{21}, v_{31}) +
  k_2 (v_{12}, v_{22}, v_{32}) +
  k_3 (v_{13}, v_{23}, v_{33})
  = (0, 0, 0)
\end{equation*}
ou
\begin{equation*}
  (k_1 v_{11} + k_2 v_{12} + k_3 v_{13},
   k_1 v_{21} + k_2 v_{22} + k_3 v_{23},
   k_1 v_{31} + k_2 v_{32} + k_3 v_{33})
  = (0, 0, 0) \\
\end{equation*}
ou encore, exprimé sous forme matricielle,
\begin{equation*}
  \begin{bmatrix}
    v_{11} & v_{12} & v_{13} \\
    v_{21} & v_{22} & v_{23} \\
    v_{31} & v_{32} & v_{33}
  \end{bmatrix}
  \begin{bmatrix}
    k_1 \\ k_2 \\ k_3
  \end{bmatrix}
  =
  \begin{bmatrix}
    0 \\ 0 \\ 0
  \end{bmatrix}.
\end{equation*}
Ainsi, un ensemble de vecteurs est linéairement indépendant si la
seule solution de l'équation homogène $\mat{Ax} = \mat{0}$, où les
colonnes de $\mat{A}$ sont formées des coordonnées des vecteurs, est
la solution triviale.



\section{Inverse d'une matrice}
\label{sec:notions:inverse}

En arithmétique usuelle, l'inverse d'un nombre $x$ est le nombre $y$
tel que $x y = 1$. Par habitude, nous écrivons simplement $y = 1/x$ ou
$y = x^{-1}$. L'inverse d'une matrice est définie de manière
similaire, sauf que l'opérateur de division n'existe pas en
arithmétique matricielle. On prendra donc garde de ne \emph{jamais}
écrire une telle abomination:
\begin{equation*}
  \mat{AB} = \mat{C} \Rightarrow \mat{A} = \frac{\mat{C}}{\mat{B}}.
\end{equation*}
Si l'on veut isoler la matrice $\mat{A}$ dans l'équation $\mat{AB} =
\mat{C}$, on ne peut que multiplier de part et d'autre par la matrice
inverse de $\mat{B}$.

\begin{definition}[Inverse d'une matrice]
  Soit $\mat{A}$ une matrice carrée. S'il existe une matrice $\mat{B}$
  tel que
  \begin{equation*}
    \mat{AB} = \mat{BA} = \mat{I},
  \end{equation*}
  alors $\mat{A}$ est inversible, $\mat{B}$ est la matrice inverse ---
  ou simplement inverse --- de $\mat{A}$ et cette dernière est notée
  $\mat{A}^{-1}$. S'il n'existe pas de matrice $\mat{B}$ satisfaisant
  l'égalité ci-dessus, alors $\mat{A}$ est dite singulière ou
  non-inversible.
\end{definition}

\begin{exemple}
  Soit l'équation $\mat{AB} = \mat{C}$. Pour isoler $\mat{A}$, il faut
  multiplier de part et d'autre de l'égalité par
  $\mat{B}^{-1}$. Attention, cependant: le produit matriciel n'étant
  pas commutatif, le produit doit se faire par la droite:
  \begin{equation*}
    (\mat{AB}) \mat{B}^{-1} = \mat{C} \mat{B}^{-1} \Leftrightarrow
    \mat{A} (\mat{B} \mat{B}^{-1}) = \mat{C} \mat{B}^{-1} \Leftrightarrow
    \mat{A} = \mat{C} \mat{B}^{-1}.
  \end{equation*}
  Pour isoler $\mat{B}$, on devra multiplier de part et d'autre de
  l'égalité par $\mat{A}^{-1}$, mais cette fois par la gauche:
  \begin{equation*}
    \mat{A}^{-1} (\mat{AB}) = \mat{A}^{-1} \mat{C} \Leftrightarrow
    (\mat{A}^{-1} \mat{A}) \mat{B} = \mat{A}^{-1} \mat{C} \Leftrightarrow
    \mat{B} = \mat{A}^{-1} \mat{C}.
  \end{equation*}
  \qed
\end{exemple}

\begin{thm}
  \label{thm:notions:inverse}
  Soit $\mat{A}$ et $\mat{B}$ des matrices inversibles de mêmes
  dimensions. Alors on a les résultats suivants.
  \begin{enumerate}
  \item $(\mat{AB})^{-1} = \mat{B}^{-1} \mat{A}^{-1}$
  \item $(\mat{A}^{-1})^T = (\mat{A}^T)^{-1}$
  \end{enumerate}
\end{thm}
\begin{proof}
  Pour le premier résultat, on doit vérifier que
  $(\mat{AB})(\mat{AB})^{-1} = \mat{I}$. Or,
  \begin{align*}
    (\mat{AB})(\mat{AB})^{-1}
    &= (\mat{AB})\mat{B}^{-1} \mat{A}^{-1} \\
    &= \mat{A} (\mat{B}\mat{B}^{-1}) \mat{A}^{-1} \\
    &= \mat{A} \mat{I} \mat{A}^{-1} \\
    &= \mat{A} \mat{A}^{-1} \\
    &= \mat{I}.
  \end{align*}
  Pour le second résultat, il faut démontrer que $(\mat{A}^{-1})^T
  \mat{A}^T = \mat{A}^T (\mat{A}^{-1})^T = \mat{I}$. Or, par le
  résultat 4 du \autoref{thm:notions:transposee}
  (\autopageref{thm:notions:transposee}),
  \begin{gather*}
    (\mat{A}^{-1})^T \mat{A}^T =
    (\mat{A} \mat{A}^{-1})^T =
    \mat{I}^T = \mat{I} \\
    \intertext{et}
    \mat{A}^T (\mat{A}^{-1})^T =
    (\mat{A}^{-1} \mat{A})^T =
    \mat{I}^T = \mat{I},
  \end{gather*}
  puisque la matrice identité est symétrique.
\end{proof}

On a également le résultat suivant, utile lorsque l'on travaille avec
les matrices élémentaires.

\begin{thm}
  \label{thm:notions:matrices_elementaires}
  Toute matrice élémentaire est inversible et son inverse est aussi
  une matrice élémentaire.
\end{thm}


\subsection{Calcul de l'inverse}

La manière la plus usuelle de calculer l'inverse d'une matrice repose
sur l'utilisation du déterminant, qui sera présenté à la
\autoref{sec:notions:determinant}. D'ici là, on peut également
calculer l'inverse d'une matrice par une méthode similaire à
l'élimination de Gauss--Jordan.

En effet, on peut démontrer que si la matrice $\mat{A}$ est
inversible, alors on peut trouver des matrices élémentaires
$\mat{E}_1, \dots, \mat{E}_k$ tel que
\begin{equation*}
  \mat{E}_k \cdots \mat{E}_1 \mat{A} = \mat{I}.
\end{equation*}
(Ce fait sera confirmé dans le \autoref{thm:notions:unification}.)
Par conséquent,
\begin{equation*}
  \mat{A}^{-1} = \mat{E}_k \cdots \mat{E}_1 \mat{I},
\end{equation*}
ce qui signifie que l'on peut obtenir l'inverse de $\mat{A}$ en
appliquant aux lignes de la matrice identité les opérations
élémentaires nécessaires pour convertir $\mat{A}$ en matrice
identité.

\begin{exemple}
  Soit la matrice
  \begin{equation*}
    \mat{A} =
    \begin{bmatrix}
      1 & 2 & 3 \\
      2 & 5 & 3 \\
      1 & 0 & 8
    \end{bmatrix}.
  \end{equation*}
  L'idée pour calculer l'inverse de cette matrice consiste à convertir
  $\mat{A}$ en la matrice identité par une suite d'opérations
  élémentaires et à appliquer simultanément ces opérations à la
  matrice identité. Pour ce faire, on joint côte à côte les matrices
  $\mat{A}$ et $\mat{I}$ dans une nouvelle matrice
  \begin{equation*}
    \setlength{\arraycolsep}{0.5em}
    [\mat{A} | \mat{I}] =
    \left[
      \begin{array}{rrr|rrr}
        1 & 2 & 3 &  1 & 0 & 0 \\
        2 & 5 & 3 &  0 & 1 & 0 \\
        1 & 0 & 8 &  0 & 0 & 1 \\
      \end{array}
    \right].
  \end{equation*}
  Suite aux opérations élémentaires, on obtiendra
  \begin{equation*}
    [\mat{I} | \mat{A}^{-1}].
  \end{equation*}
  La procédure est la suivante:
  \begin{enumerate}
  \item Additionner $-2$ fois la première ligne à la seconde et $-1$
    fois à la troisième:
    \begin{equation*}
      \setlength{\arraycolsep}{0.5em}
      \left[
        \begin{array}{rrr|rrr}
          1 &  2 &  3 &   1 &  0 &  0 \\
          0 &  1 & -3 &  -2 &  1 &  0 \\
          0 & -2 &  5 &  -1 &  0 &  1
        \end{array}
      \right]
    \end{equation*}
  \item Additionner 2 fois la seconde ligne à la troisième, puis
    multiplier celle-ci par $-1$:
    \begin{equation*}
      \left[
        \begin{array}{rrr|rrr}
          1 &  2 &  3 &   1 &  0 &  0 \\
          0 &  1 & -3 &  -2 &  1 &  0 \\
          0 &  0 &  1 &   5 & -2 &  -1 \\
        \end{array}
      \right].
    \end{equation*}
  \item Additionner 3 fois la troisième ligne à la seconde et $-3$
    fois à la première:
    \begin{equation*}
      \left[
        \begin{array}{rrr|rrr}
          1 &  2 &  0 &  -14 &  6 &  3 \\
          0 &  1 &  0 &   13 & -5 & -3 \\
          0 &  0 &  1 &    5 & -2 & -1 \\
        \end{array}
      \right].
    \end{equation*}
  \item Additionner $-2$ fois la seconde ligne à la première:
    \begin{equation*}
      \left[
        \begin{array}{rrr|rrr}
          1 &  0 &  0 &  -40 & 16 &  9 \\
          0 &  1 &  0 &   13 & -5 & -3 \\
          0 &  0 &  1 &    5 & -2 & -1 \\
        \end{array}
      \right].
    \end{equation*}
  \end{enumerate}
  Par conséquent,
  \begin{equation*}
    \mat{A}^{-1} =
    \begin{bmatrix}
      -40 & 16 &  9 \\
       13 & -5 & -3 \\
        5 & -2 & -1
    \end{bmatrix}.
  \end{equation*}
  \qed
\end{exemple}

\begin{exemple}
  Soit la matrice
  \begin{equation*}
    \mat{A} =
    \begin{bmatrix}
       1 & 6 &  4 \\
       2 & 4 & -1 \\
      -1 & 2 &  5
    \end{bmatrix}.
  \end{equation*}
  Il est laissé en exercice de vérifier que la procédure d'élimination
  pour les deuxième et troisième lignes donne
  \begin{equation*}
    \left[
      \begin{array}{rrr|rrr}
        1 &  6 &  4 &  1 &  0 &  0 \\
        0 & -8 & -9 & -2 &  1 &  0 \\
        0 &  0 &  0 & -1 &  1 &  1 \\
      \end{array}
    \right].
  \end{equation*}
  Comme on obtient une ligne complète de zéros du côté gauche, la
  matrice est singulière.
  \qed
\end{exemple}

\subsection{Résolution de systèmes d'équations par l'inverse}

Outre l'élimination gaussienne et l'élimination de Gauss--Jordan, les
systèmes d'équations linéaires de la forme $\mat{Ax} = \mat{b}$
peuvent être résolus avec l'inverse de $\mat{A}$, lorsqu'elle existe.

\begin{thm}
  \label{thm:notions:sol.inverse}
  Si la matrice $\mat{A}$ est inversible, alors le système d'équations
  linéaires $\mat{Ax} = \mat{b}$ a une solution unique et celle-ci est
  donnée par
  \begin{equation*}
    \mat{x} = \mat{A}^{-1} \mat{b}.
  \end{equation*}
\end{thm}

Le résultat ci-dessus ne peut évidemment servir que lorsque le système
d'équations compte autant d'inconnues que d'équations, c'est-à-dire
lorsque la matrice $\mat{A}$ est carrée. Dans le cas contraire, il
faut utiliser les méthodes d'élimination pour résoudre le système
d'équations.



\section{Déterminant}
\label{sec:notions:determinant}

La fonction déterminant, notée $\det(\cdot)$, associe un nombre réel à
une matrice carrée $\mat{A}$.

Il y a différentes façons de présenter le déterminant, nous ne
retiendrons que celle basée sur les cofacteurs. Pour ce faire, on
définit tout d'abord le déterminant d'une matrice $2 \times 2$, ainsi
que son inverse. La justification de ce second résultat viendra plus
loin.

\begin{thm}
  \label{thm:notions:det.2x2}
  Soit $\mat{A} = \bigl( \begin{smallmatrix} a&b \\ c&d
  \end{smallmatrix} \bigr)$. Alors
  \begin{align*}
    \det(\mat{A})
    &=
    \begin{vmatrix}
      a & b \\ c & d
    \end{vmatrix} = ad - bc \\
    \intertext{et}
    \mat{A}^{-1}
    &= \frac{1}{ad - bc}
    \begin{bmatrix}
      d & -b \\ -c & a
    \end{bmatrix}.
  \end{align*}
\end{thm}

Soit $\mat{A} = [a_{ij}]_{n \times n}$ une matrice carrée. Le
\emph{mineur de l'élément $a_{ij}$}, noté $M_{ij}$, est le déterminant
de la sous-matrice résultante après avoir éliminé la ligne $i$ et la
colonne $j$ de la matrice $\mat{A}$. De plus, le \emph{cofacteur de
  l'élément $a_{ij}$} est $C_{ij} = (-1)^{i + j} M_{ij}$.

\begin{exemple}
  \label{ex:notions:cofacteur}
  Soit
  \begin{equation*}
    \mat{A} =
    \begin{bmatrix}
      3 & 1 & -4 \\
      2 & 5 &  6 \\
      1 & 4 &  8
    \end{bmatrix}.
  \end{equation*}
  Une fois la première ligne et la première colonne éliminées de la
  matrice $\mat{A}$, on a
  \begin{equation*}
    M_{11} =
    \begin{vmatrix}
      5 & 6 \\ 4 & 8
    \end{vmatrix} = 16,
  \end{equation*}
  d'où $C_{11} = (-1)^2 M_{11} = M_{11} = 16$. De même, après avoir
  éliminé la troisième ligne et la deuxième colonne, on obtient
  \begin{equation*}
    M_{32} =
    \begin{vmatrix}
      3 & -4 \\ 2 & 6
    \end{vmatrix} = 26
  \end{equation*}
  et $C_{32} = (-1)^{3+2} M_{32} = - M_{32} = -26$.
  \qed
\end{exemple}

Le déterminant d'une matrice $\mat{A}$ est le produit scalaire entre
les éléments d'une ligne ou d'une colonne quelconque de la matrice et
les cofacteurs de cette ligne ou colonne.

\begin{thm}
  \label{thm:notions:determinant}
  Soit $\mat{A}$ une matrice carrée $n \times n$. Alors, pour tout $1
  \leq i \leq n$ et $1 \leq j \leq n$,
  \begin{align*}
    \det(\mat{A})
    &= a_{i1} C_{i1} + a_{i2} C_{i2} + \dots + a_{in} C_{in} \\
    &= \sum_{j = 1}^n a_{ij} C_{ij} \\
    \intertext{ou}
    \det(\mat{A})
    &= a_{1j} C_{1j} + a_{2j} C_{2j} + \dots + a_{nj} C_{nj} \\
    &= \sum_{i = 1}^n a_{ij} C_{ij}.
  \end{align*}
\end{thm}

\begin{exemple}
  On calcule le déterminant de la matrice de l'\autoref{ex:notions:cofacteur}.  En faisant le calcul à partir de la
  première ligne, on a
  \begin{align*}
    \det(\mat{A})
    &= 3 (-1)^2 \begin{vmatrix} 5 & 6 \\ 4 & 8 \end{vmatrix}
    + (-1)^3 \begin{vmatrix} 2 & 6 \\ 1 & 8 \end{vmatrix}
    + (-4) (-1)^4 \begin{vmatrix} 2 & 5 \\ 1 & 4 \end{vmatrix} \\
    &= 3 \begin{vmatrix} 5 & 6 \\ 4 & 8 \end{vmatrix}
    - \begin{vmatrix} 2 & 6 \\ 1 & 8 \end{vmatrix}
    -4 \begin{vmatrix} 2 & 5 \\ 1 & 4 \end{vmatrix} \\
    &= 3(16) - 10 - 4(3) \\
    &= 26.
  \end{align*}
  On obtient la même réponse avec un développement selon la deuxième
  colonne:
  \begin{align*}
    \det(\mat{A})
    &= - \begin{vmatrix} 2 & 6 \\ 1 & 8 \end{vmatrix}
    + 5 \begin{vmatrix} 3 & -4 \\ 1 & 8 \end{vmatrix}
    - 4 \begin{vmatrix} 3 & -4 \\ 2 & 6 \end{vmatrix} \\
    &= -10 + 5(28) - 4(26) \\
    &= 26.
  \end{align*}
  \qed
\end{exemple}


\subsection{Propriétés du déterminant}

Du \autoref{thm:notions:determinant}, il est clair que si une
matrice contient une ligne ou une colonne complète de zéros, alors son
déterminant est nul.

De plus, si $\mat{A}$ est une matrice triangulaire (ou diagonale),
alors son déterminant est égal au produit des éléments de la
diagonale:
\begin{equation*}
  \det(\mat{A}) = \prod_{i=1}^n a_{ii}.
\end{equation*}

Le théorème suivant énonce quelques autres propriétés de la fonction
déterminant.

\begin{thm}
  \label{thm:notions:prop.determinant}
  Soit $\mat{A}$ une matrice $n \times n$ inversible.
  \begin{enumerate}
  \item $\det(\mat{A}^T) = \det(\mat{A})$
  \item $\det(k\mat{A}) = k^n \det(\mat{A})$
  \item $\det(\mat{A} + \mat{B}) \neq \det(\mat{A}) + \det(\mat{B})$
    en général.
  \item $\det(\mat{A}\mat{B}) = \det(\mat{A}) \det(\mat{B})$
  \item $\det(\mat{A}^{-1}) = \det(\mat{A})^{-1}$
  \end{enumerate}
\end{thm}


\subsection{Calcul de l'inverse avec la matrice adjointe}

La manière de loin la plus usuelle de calculer l'inverse d'une matrice
--- à la main du moins --- est intimement liée aux notions de
cofacteur et de déterminant.

Avant toute chose, on définit $[C_{ij}]_{n \times n}$, la
\emph{matrice des cofacteurs} de la matrice $\mat{A}$. La transposée
de cette matrice des cofacteurs est appelée la \emph{matrice adjointe}
de $\mat{A}$ et est notée $\mathrm{adj}(\mat{A})$.

\begin{exemple}
  Il est laissé en exercice de vérifier que la matrice adjointe de la
  matrice de l'\autoref{ex:notions:cofacteur} est
  \begin{equation*}
    \begin{bmatrix}
       16 & -24 &  26 \\
      -10 &  28 & -26 \\
        3 & -11 &  13
    \end{bmatrix}.
  \end{equation*}
  \qed
\end{exemple}

\begin{thm}
  \label{thm:notions:inverse.adjointe}
  Si $\mat{A}$ est une matrice inversible, alors
  \begin{equation*}
    \mat{A}^{-1} = \frac{1}{\det(\mat{A})}\, \mathrm{adj}(\mat{A}).
  \end{equation*}
\end{thm}



\section{Rang}
\label{sec:notions:rang}

Le \emph{rang} d'une matrice $\mat{A}_{m \times n}$ correspond au
nombre de lignes ou de colonnes linéairement indépendantes dans cette
matrice. Évidemment,
\begin{equation*}
  \mathrm{rang}(\mat{A}) \leq \min(m, n).
\end{equation*}
Lorsqu'il y a égalité, on dit de la matrice qu'elle est de rang
complet.



\section{Unification des résultats}
\label{sec:notions:unification}

Le théorème suivant unifie un grand nombre de résultats et de concepts
présentés dans les sections précédentes. En ce sens, il fait le
sommaire des plus importants résultats à connaître en algèbre linéaire.

\begin{thm}
  \label{thm:notions:unification}
  Soit $\mat{A}$ une matrice $n \times n$. Les énoncés suivants
  sont équivalents.
  \begin{enumerate}[widest=10]
  \item $\mat{A}$ est inversible.
  \item $\det(\mat{A}) \neq 0$
  \item $\mathrm{rang}(\mat{A}) = n$
  \item La seule solution de $\mat{Ax} = \mat{0}$ est la solution
    triviale.
  \item Le système d'équations $\mat{Ax} = \mat{b}$ a une solution
    pour tout vecteur $\mat{b}$ et celle-ci est unique.
  \item $\mat{A}$ peut être exprimée comme un produit de matrices
    élémentaires.
  \item Les vecteurs lignes de $\mat{A}$ sont linéairement
    indépendants.
  \item Les vecteurs colonnes de $\mat{A}$ sont linéairement
    indépendants.
  \item Les vecteurs lignes de $\mat{A}$ forment une base de $\R^n$.
  \item Les vecteurs colonnes de $\mat{A}$ forment une base de $\R^n$.
  \end{enumerate}
\end{thm}

\gotorbox{Le code informatique de la \autoref{sec:notions:code} passe en
  revue les fonctions d'algèbre linéaire offertes dans R.}%


\section{Code informatique}
\label{sec:notions:code}

\def\scriptfilename{notions\string_fondamentales.R}

\scriptfile{\scriptfilename}
\lstinputlisting[firstline=13]{\scriptfilename}


\section{Exercices}
\label{chap:notions:exercices}

\Opensolutionfile{reponses}[reponses-notions_fondamentales]
\Opensolutionfile{solutions}[solutions-notions_fondamentales]

\begin{Filesave}{reponses}
\bigskip
\section*{Réponses}

\end{Filesave}

\begin{Filesave}{solutions}
\section*{Chapitre \ref*{chap:notions}}
\addcontentsline{toc}{section}{Chapitre \ref*{chap:notions}}

\end{Filesave}

\begin{exercice}
  Pour chaque cas ci-dessous, supposer que la matrice donnée est
  une matrice augmentée d'un système d'équations linéaires exprimée
  sous forme échelonnée. Résoudre le système d'équations.
  \begin{enumerate}
    \begin{multicols}{2}
    \item $%
      \begin{bmatrix}
        1 & -3 & 4 & 7 \\
        0 & 1 & 2 & 2 \\
        0 & 0 & 1 & 5
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        1 & 0 & 8 & -5 & 6 \\
        0 & 1 & 4 & -9 & 3 \\
        0 & 0 & 1 & 1 & 2
      \end{bmatrix}$
    \end{multicols}
    \begin{multicols}{2}
    \item $%
      \begin{bmatrix}
        1 & 7 & -2 & 0 & -8 & -3 \\
        0 & 0 & 1 & 1 & 6 & 5 \\
        0 & 0 & 0 & 1 & 3 & 9 \\
        0 & 0 & 0 & 0 & 0 & 0
      \end{bmatrix}$
      \columnbreak
    \item $%
      \begin{bmatrix}
        1 & -3 & 7 & 1 \\
        0 & 1 & 4 & 0 \\
        0 & 0 & 0 & 1
      \end{bmatrix}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item On a une solution unique. Le système d'équations
      correspondant est
      \begin{align*}
        x_1 - 3 x_2 + 4 x_3 &= 7 \\
        x_2 + 2 x_3 &= 2 \\
        x_3 &= 5.
      \end{align*}
      Par substitution successive, on obtient $x_3 = 5$, $x_2 = 2 - 2(5)
      = -8$ et $x_1 = 7 + (3)(-8) - 4(5) = -37$.
    \item Le système est sous-déterminé puisqu'il compte plus d'inconnues
      que d'équations. Il y a donc une infinité de solutions. Le
      système d'équations correspondant est
      \begin{align*}
        x_1 + 8 x_3 - 5 x_3 &= 6 \\
        x_2 + 4 x_3 - 9 x_4 &= 3 \\
        x_3 + x_4 &= 2.
      \end{align*}
      On utilise la variable libre $x_4 = t$. Ainsi, la solution
      générale du système d'équations est $x_3 = 2 - t$, $x_2 = 3 -
      4(2 - t) + 9t = -5 + 13t$ et $x_1 = 6 - 8 (2 - t) + 5 t = -10 +
      13t$.
    \item On avait à l'origine un système d'équations à quatre
      équations et cinq inconnues. La matrice échelonnée contient une
      ligne complète de zéros, ce qui indique que la quatrième
      équation était une combinaison linéaire des trois autres. Ne
      reste donc qu'un système sous-déterminé à trois équations et
      cinq inconnues:
      \begin{align*}
        x_1 + x_2 - 2 x_3 - 8 x_5 &= -3 \\
        x_3 + x_4 + 6 x_5 &= 5 \\
        x_4 + 3 x_5 &= 9.
      \end{align*}
      Ce système a une infinité de solutions et il faudra, pour les
      exprimer, poser deux variables libres. Les candidates sont les
      variables correspondant aux colonnes sans un 1 sur la diagonale.
      On pose donc $x_2 = s$ et $x_5 = t$. On a alors $x_4 = 9 - 3t$,
      $x_3 = 5 - (9 - 3t) - 6 t = -4 - 3t$ et $x_1 = -3 - 7s + 2 (-4 -
      3t) + 8 t = -11 - 7s + 2t$.
    \item La dernière ligne de la matrice échelonnée correspond à
      l'équation impossible à satisfaire
      \begin{displaymath}
        0 x_1 + 0 x_2 + 0 x_3 = 1,
      \end{displaymath}
      d'où le système n'a pas de solution.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{enumerate}
    \item $x_1 = -37$, $x_2 = -8$, $x_3 = 5$
    \item $x_1 = -10 + 13t$, $x_2 = -5 + 13t$, $x_3 = 2 - t$, $x_4 =
      t$
    \item $x_1 = -11 - 7s + 2t$, $x_2 = s$, $x_3 = -4 - 3t$, $x_4 = 9 -
      3t$, $x_5 = t$
    \item pas de solution
    \end{enumerate}
  \end{rep}
\end{exercice}

\begin{exercice}
  \label{ex:notions:reduction}
  Résoudre chacun des systèmes d'équations suivants par
  l'élimination gaussienne et l'élimination de Gauss--Jordan.
  \begin{enumerate}
    \begin{multicols}{2}
    \item $%
      \begin{array}[t]{*{2}{r@{\;}c@{\;}}r@{\;=\;}r}
        x_1 &+&  x_2 &+& 2x_3 &  8 \\
        -x_1 &-& 2x_2 &+& 3x_3 &  1 \\
        3x_1 &-& 7x_2 &+& 4x_3 & 10
      \end{array}$
    \item $%
      \begin{array}[t]{*{2}{r@{\;}c@{\;}}r@{\;=\;}r}
        2x_1 &+& 2x_2 &+& 2x_3 &  0 \\
        -2x_1 &+& 5x_2 &+& 2x_3 &  1 \\
        8x_1 &+&  x_2 &+& 4x_3 & -1
      \end{array}$
    \end{multicols}
    \begin{multicols}{2}
    \item $%
      \begin{array}[t]{*{3}{r@{\;}c@{\;}}r@{\;=\;}r}
        x &-&  y &+& 2z &-&  w & -1 \\
        2x &+&  y &-& 2z &-& 2w & -2 \\
        -x &+& 2y &-& 4z &+&  w & 1 \\
        3x & &    & &    &-& 3w & -3
      \end{array}$
    \item $%
      \begin{array}[t]{*{2}{r@{\;}c@{\;}}r@{\;=\;}r}
        &-& 2b &+& 3c & 1 \\
        3a &+& 6b &-& 3c & -2 \\
        6a &+& 6b &+& 3c & 5
      \end{array}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item On donne la solution pour l'élimination gaussienne
      seulement. La matrice augmentée est
      \begin{displaymath}
        \begin{bmatrix}
           1 &  1 &  2 &  8 \\
          -1 & -2 &  3 &  1 \\
           3 & -7 &  4 & 10
         \end{bmatrix}.
      \end{displaymath}
      Les opérations élémentaires à effectuer sur cette matrice pour
      l'exprimer sous forme échelonnée sont, dans l'ordre:
      \begin{enumerate}[1.]
      \item additionner la première ligne à la seconde;
      \item additionner $-3$ fois la première ligne à la troisième;
      \item additionner $-3$ fois la première ligne à la troisième;
      \item multiplier la deuxième ligne par $-1$;
      \item additionner $10$ fois la deuxième ligne à la troisième;
      \item diviser la troisième ligne par $-52$.
      \end{enumerate}
      On obtient alors la matrice échelonnée
      \begin{displaymath}
        \begin{bmatrix}
          1 &  1 &  2 &  8 \\
          0 &  1 & -5 & -9 \\
          0 &  0 &  1 &  2
         \end{bmatrix},
      \end{displaymath}
      d'où $x_3 = 2$, $x_2 = -9 + 5(2) = 1$ et $x_1 = 8 - 1 - 2(2) =
      3$.
    \item On donne la solution pour l'élimination de Gauss--Jordan
      seulement. La matrice augmentée est
      \begin{displaymath}
        \begin{bmatrix}
           2 &  2 &  2 &  0 \\
          -2 &  5 &  2 &  1 \\
           8 &  1 &  4 & -1
         \end{bmatrix}.
      \end{displaymath}
      Les opérations élémentaires à effectuer sur cette matrice pour
      l'exprimer sous forme échelonnée réduite sont les suivantes:
      \begin{enumerate}[1.]
      \item multiplier la première ligne par $\frac{1}{2}$;
      \item additionner 2 fois la première ligne à la deuxième;
      \item additionner $-8$ fois la première ligne à la troisième;
      \item additionner la deuxième ligne à la troisième;
      \item multiplier la deuxième ligne par $\frac{1}{7}$;
      \item additionner $-1$ fois la deuxième ligne à la première.
      \end{enumerate}
      On obtient alors la matrice échelonnée réduite
      \begin{displaymath}
        \begin{bmatrix}
           1 &  0 & 3/7 & -1/7 \\
           0 &  1 & 4/7 & 1/7 \\
           0 &  0 &   0 &   0
         \end{bmatrix}.
      \end{displaymath}
      En posant $x_3 = t$, on a la solution générale $x_2 =
      \frac{1}{7} - \frac{4}{7}t$ et $x_1 = -\frac{1}{7} -
      \frac{3}{7}t$.
    \item On donne la solution pour l'élimination gaussienne
      seulement. La matrice augmentée est
      \begin{displaymath}
        \begin{bmatrix}
           1 & -1 &  2 & -1 & -1 \\
           2 &  1 & -2 & -2 & -2 \\
          -1 &  2 & -4 &  1 &  1 \\
           3 &  0 &  0 & -3 & -3
         \end{bmatrix}.
      \end{displaymath}
      Les opérations élémentaires à effectuer sur cette matrice pour
      l'exprimer sous forme échelonnée sont, dans l'ordre:
      \begin{enumerate}[1.]
      \item additionner $-2$ fois la première ligne à la seconde;
      \item additionner la première ligne à la troisième;
      \item additionner $-3$ fois la première ligne à la quatrième;
      \item additionner $-1$ fois la deuxième ligne à la quatrième;
      \item multiplier la deuxième ligne par $\frac{1}{3}$;
      \item additionner $-1$ fois la deuxième ligne à la troisième.
      \end{enumerate}
      On obtient alors la matrice échelonnée
      \begin{displaymath}
        \begin{bmatrix}
           1 & -1 &  2 & -1 & -1 \\
           0 &  1 & -2 &  0 &  0 \\
           0 &  0 &  0 &  0 &  0 \\
           0 &  0 &  0 &  0 &  0
         \end{bmatrix},
      \end{displaymath}
      d'où $x_3 = s$, $x_4 = t$, $x_2 = 2s$ et $x_1 = -1 + 2s - 2s + t
      = -1 + t$.
    \item En échangeant les première et troisième équations, on a la
      matrice augmentée
      \begin{displaymath}
        \begin{bmatrix}
          6 &  6 &  3 &  5 \\
          3 &  6 & -3 & -2 \\
          0 & -2 &  3 &  1
        \end{bmatrix}.
      \end{displaymath}
      Après les opérations élémentaires
      \begin{enumerate}[1.]
      \item multiplier la première ligne par $\frac{1}{6}$;
      \item additionner $-3$ fois la première ligne à la deuxième;
      \item multiplier la deuxième ligne par $\frac{1}{3}$;
      \item additionner 2 fois la deuxième ligne à la troisième,
      \end{enumerate}
      on obtient la matrice échelonnée
      \begin{displaymath}
        \begin{bmatrix}
          1 &  1 &  1/2 &  5/6 \\
          0 &  1 & -3/2 & -3/2 \\
          0 &  0 &    0 &   -2
        \end{bmatrix}.
      \end{displaymath}
      La troisième équation étant impossible à satisfaire, le système
      n'a pas de solution.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{enumerate}
    \item $x_1 = 3$, $x_2 = 1$, $x_3 = 2$
    \item $x_1 = -\frac{1}{7} - \frac{3}{7}t$,
          $x_2 = \frac{1}{7} -  \frac{4}{7}t$,
          $x_3 = t$
    \item $x_1 = t - 1$, $x_2 = 2s$, $x_3 = s$, $x_4 = t$
    \item pas de solution
    \end{enumerate}
  \end{rep}
\end{exercice}

\enlargethispage{5mm}

\begin{exercice}
  Résoudre chacun des systèmes d'équations suivants par l'élimination
  gaussienne et l'élimination de Gauss--Jordan.
  \begin{enumerate}
    \begin{multicols}{2}
    \item $%
      \begin{array}[t]{*{2}{r@{\;}c@{\;}}r@{\;=\;}r}
        5x_1 &-& 2x_2 &+& 6x_3 & 0 \\
        -2x_1 &+&  x_2 &+& 3x_3 & 1
      \end{array}$
    \item $%
      \begin{array}[t]{*{3}{r@{\;}c@{\;}}r@{\;=\;}r}
        x_1 &-&  2x_2 &+&   x_3 &-&  4x_4 & 1 \\
        x_1 &+&  3x_2 &+&  7x_3 &+&  2x_4 & 2 \\
        x_1 &-& 12x_2 &-& 11x_3 &-& 16x_4 & 5
      \end{array}$
    \end{multicols}
    \begin{multicols}{2}
    \item $%
      \begin{array}[t]{*{4}{r@{\;}c@{\;}}r@{\;=\;}r}
        & &    & &  w &+& 2x &-&  y & 4 \\
        & &    & &    & &  x &-&  y & 3 \\
        & &    & &  w &+& 3x &-& 2y & 7 \\
        2u &+& 4v &+&  w &+& 7x & &    & 7
      \end{array}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    La procédure de réduction des matrices augmentées sous forme
    échelonnée est similaire à celle utilisée dans les solutions de
    l'\autoref{ex:notions:reduction}. On ne donne, ici que les
    résultats de cette procédure.
    \begin{enumerate}
    \item La matrice échelonnée est
      \begin{displaymath}
        \begin{bmatrix}
          1 & -2/5 & 6/5 & 0 \\
          0 &    1 &  27 & 5
        \end{bmatrix}
      \end{displaymath}
      et la matrice échelonnée réduite est
      \begin{displaymath}
        \begin{bmatrix}
          1 & 0 & 12 & 2 \\
          0 & 1 & 27 & 5
        \end{bmatrix}.
      \end{displaymath}
      Par conséquent, la solution générale est $x_3 = t$, $x_2 = 5 -
      27t$ et $x_1 = 2 - 12t$.
    \item La matrice échelonnée réduite est
      \begin{displaymath}
        \begin{bmatrix}
          1 & -2 &   1 &  -4 & 1 \\
          0 &  1 & 6/5 & 6/5 & 1/5 \\
          0 &  0 &   0 &   0 &   6
        \end{bmatrix}.
      \end{displaymath}
      Ce système n'a donc pas de solution.
    \item La matrice échelonnée est
      \begin{displaymath}
        \begin{bmatrix}
          1 & 2 & 1/2 & 7/2 &  0 & 7/2 \\
          0 & 0 &   1 &   2 & -1 &   4 \\
          0 & 0 &   0 &   1 & -1 &   3 \\
          0 & 0 &   0 &   0 &  0 &   0
        \end{bmatrix}
      \end{displaymath}
      et la matrice échelonnée réduite est
      \begin{displaymath}
        \begin{bmatrix}
          1 & 2 &   0 &   0 &  3 &  -6 \\
          0 & 0 &   1 &   0 &  1 &  -2 \\
          0 & 0 &   0 &   1 & -1 &   3 \\
          0 & 0 &   0 &   0 &  0 &   0
        \end{bmatrix}.
      \end{displaymath}
      Par conséquent, la solution générale est $v = s$, $y = t$, $x =
      3 + t$, $w = -2 - t$ et $u = -6 - 3t - 2s$.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{enumerate}
    \item $x_1 = 2 - 12t$, $x_2 = 5 - 27t$, $x_3 = t$
    \item pas de solution
    \item $u = -2s - 3t - 6$,
          $v = s$,
          $w = -t - 2$,
          $x = t + 3$,
          $y = t$
    \end{enumerate}
  \end{rep}
\end{exercice}

\begin{exercice}
  Résoudre les systèmes d'équations homogènes suivants.
  \begin{enumerate}
    \begin{multicols}{2}
    \item $%
      \begin{array}[t]{*{2}{r@{\;}c@{\;}}r@{\;=\;}r}
        2x_1 &+&  x_2 &+& 3x_3 & 0 \\
        x_1 &+& 2x_2 & &      & 0 \\
        & &  x_2 &+&  x_3 & 0
      \end{array}$
    \item $%
      \begin{array}[t]{*{3}{r@{\;}c@{\;}}r@{\;=\;}r}
        3x_1 &+&   x_2 &+&  x_3 &+&  x_4 & 0 \\
        5x_1 &-&   x_2 &+&  x_3 &-&  x_4 & 0
      \end{array}$
    \end{multicols}
    \begin{multicols}{2}
    \item $%
      \begin{array}[t]{*{3}{r@{\;}c@{\;}}r@{\;=\;}r}
        & & 2x &+& 2y &+& 4z & 0 \\
        w & &    &-&  y &-& 3z & 0 \\
        2w &+& 3x &+&  y &+&  z & 0 \\
        -2w &+&  x &+& 3y &-& 2z & 0
      \end{array}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item Après quelques opérations élémentaires sur les lignes de la
      matrice augmentée correspondant à ce système d'équations, on
      obtient
      \begin{displaymath}
        \begin{bmatrix}
          2 & 1 &  3 & 0 \\
          0 & 3 & -3 & 0 \\
          0 & 0 &  6 & 0
        \end{bmatrix},
      \end{displaymath}
      d'où $x_3 = x_2 = x_1 = 0$, soit la solution triviale.
    \item La somme des deux équations donne une nouvelle équation
      $4x_1 + x_3 = 0$, d'où $x_3 = -4 x_1$. De la première équation,
      on a également $x_2 = -3 x_1 - x_3 - x_4 = x_1 - x_4$. En
      posant $x_1 = -s$ et $x_4 = t$, on a la solution générale $x_3
      = 4 s$ et $x_2 = -s - t$. Il y a évidemment de multiples autres
      façons d'exprimer la solution générale en utilisant des
      variables libres différentes.
    \item La matrice échelonnée de ce système d'équations est
      \begin{displaymath}
        \begin{bmatrix}
          1 & 0 & -1 &  -3 \\
          0 & 1 &  1 & 7/3 \\
          0 & 0 &  0 &   1 \\
          0 & 0 &  0 &   1
        \end{bmatrix}.
      \end{displaymath}
      On a donc $z = 0$ et, en posant $y = t$, $x = -t$, $w = t$.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{enumerate}
    \item solution triviale
    \item $x_1 = -s$, $x_2 = -t - s$, $x_3 = 4s$, $x_4 = t$
    \item $w = t$, $x = -t$, $y = t$, $z = 0$
    \end{enumerate}
  \end{rep}
\end{exercice}

\begin{exercice}
  Pour quelle valeur de $a$ le système d'équations
  \begin{displaymath}
    \begin{array}{*{2}{r@{\;}c@{\;}}r@{\;=\;}l}
       x &+& 2y &-&          3z & 4 \\
      3x &-&  y & &          5z & 2 \\
      4x &+&  y &+& (a^2 - 14)z & a + 2
    \end{array}
  \end{displaymath}
  n'aura-t-il aucune solution? Une seule solution? Une infinité de
  solutions?
  \begin{sol}
    Après des opérations élémentaires sur la matrice augmentée du
    système d'équations, on obtient
    \begin{displaymath}
      \begin{bmatrix}
        1 &  2 &        3 & 4 \\
        0 & -7 &       14 & -10 \\
        0 &  0 & a^2 - 16 & a - 4
      \end{bmatrix}.
    \end{displaymath}
    On constate alors que le système d'équations n'a pas de solution
    si $a^2 - 16 = 0$ et $a - 4 \neq 0$, donc lorsque $a = -4$. En
    revanche, si $a^2 - 16 = 0$ et $a - 4 = 0$, soit lorsque $a = 4$,
    le système a une infinité de solutions. Finalement, si $a^2 - 16
    \neq 0 \Leftrightarrow |a| \neq 4$, le système a une solution
    unique.
  \end{sol}
  \begin{rep}
    Aucune solution: $a = -4$. Une seule solution: $a \neq \pm 4$.
    Infinité de solutions: $a = 4$.
  \end{rep}
\end{exercice}

\begin{exercice}
  Soit les matrices $\mat{A}_{4 \times 5}$, $\mat{B}_{4 \times 5}$,
  $\mat{C}_{5 \times 2}$, $\mat{D}_{4 \times 2}$ et $\mat{E}_{5 \times
    4}$. Lesquelles des expressions matricielles suivantes sont
  définies?  Pour les expressions définies, donner les dimensions de
  la matrice résultante.
  \begin{enumerate}
    \begin{multicols}{4}
    \item $\mat{BA}$
    \item $\mat{AC} + \mat{D}$
    \item $\mat{AE} + \mat{B}$
    \item $\mat{AB} + \mat{B}$
    \end{multicols}
    \vspace{-1.5\baselineskip}
    \begin{multicols}{4}
    \item $\mat{E}(\mat{A} + \mat{B})$
    \item $\mat{E}(\mat{AC})$
    \item $\mat{E}^T \mat{A}$
    \item $(\mat{A}^T + \mat{E})\mat{D}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    La somme (ou la différence) entre deux matrices est définie si les
    dimensions des matrices sont identiques. Les dimensions du
    résultat seront les mêmes. Quant au produit, il est défini si le
    nombre de colonnes de la première matrice est égal au nombre de
    lignes de la seconde; le résultat est une matrice dont le nombre
    de lignes est égal à celui de la première matrice et le nombre de
    colonnes à celui de la seconde matrice.
    \begin{enumerate}
    \item Le produit $\mat{B} \mat{A}$ n'est pas défini.
    \item Le résultat de $\mat{A} \mat{C}$ est une matrice $4 \times
      2$, donc l'opération $\mat{A} \mat{C} + \mat{D}$ est définie et
      le résultat est une matrice $4 \times 2$.
    \item Le résultat de $\mat{A} \mat{E}$ est une matrice $4 \times
      4$, donc l'opération $\mat{A} \mat{E} + \mat{B}$ n'est pas
      définie.
    \item Le produit $\mat{A} \mat{B}$ n'est pas défini.
    \item La somme $\mat{A} + \mat{B}$ est définie, tout comme le
      produit $\mat{E}(\mat{A} + \mat{B})$. Le résultat est une
      matrice $5 \times 5$.
    \item Le résultat du produit $\mat{A} \mat{C}$ est une matrice $4
      \times 2$, donc $\mat{E}(\mat{AC})$ est une matrice $5 \times 2$.
    \item Puisque $\mat{E}^T$ est une matrice $4 \times 5$, le produit
      $\mat{E}^T \mat{A}$ n'est pas défini.
    \item Le résultat de $\mat{A}^T + \mat{E}$ est une matrice $5
      \times 4$, donc $(\mat{A}^T + \mat{E}) \mat{D}$ est une matrice
      $5 \times 2$.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{inparaenum}
    \item non défini
    \item $4 \times 2$
    \item non défini
    \item non défini
    \item $5 \times 5$
    \item $5 \times 2$
    \item non défini
    \item $5 \times 2$
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Soit les matrices
  \begin{align*}
    \mat{A}
    &=
    \begin{bmatrix}
      3 & 0 \\ -1 & 2 \\ 1 & 1
    \end{bmatrix} &
    \mat{B}
    &=
    \begin{bmatrix}
      4 & -1 \\ 0 & 2
    \end{bmatrix} &
    \mat{C}
    &=
    \begin{bmatrix}
      1 & 4 & 2 \\ 3 & 1 & 5
    \end{bmatrix} \\
    \mat{D}
    &=
    \begin{bmatrix}
      1 & 5 & 2 \\ -1 & 0 & 1 \\ 3 & 2 & 4
    \end{bmatrix} &
    \mat{E}
    &=
    \begin{bmatrix}
      6 & 1 & 3 \\ -1 & 1 & 2 \\ 4 & 1 & 3
    \end{bmatrix}.
  \end{align*}
  Calculer les expressions suivantes (lorsque possible).
  \begin{enumerate}
    \begin{multicols}{2}
    \item $\mat{D} + \mat{E}$
    \item $\mat{AB}$
    \end{multicols}
    \vspace{-1.5\baselineskip}
    \begin{multicols}{2}
    \item $(2 \mat{D}^T - \mat{E}) \mat{A}$
    \item $(4 \mat{B}) \mat{C} + 2 \mat{B}$
    \end{multicols}
    \vspace{-1.5\baselineskip}
    \begin{multicols}{2}
    \item $(-\mat{AC})^T + 5 \mat{D}^T$
    \item $(\mat{BA}^T - 2 \mat{C})^T$
    \end{multicols}
    \vspace{-1.5\baselineskip}
    \begin{multicols}{2}
    \item $\mat{B}^T (\mat{CC}^T - \mat{A}^T \mat{A})$
    \item $\mat{D}^T \mat{E}^T - (\mat{ED})^T$
    \end{multicols}
    \vspace{-1.5\baselineskip}
    \begin{multicols}{2}
    \item $\tr(\mat{DD}^T)$
    \item $\tr(4 \mat{E}^T - \mat{D})$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item On a
      \begin{displaymath}
        \mat{D} + \mat{E}
        =
        \begin{bmatrix}
          1 & 5 & 2 \\ -1 & 0 & 1 \\ 3 & 2 & 4
        \end{bmatrix} +
        \begin{bmatrix}
          6 & 1 & 3 \\ -1 & 1 & 2 \\ 4 & 1 & 3
        \end{bmatrix}
        =
        \begin{bmatrix}
          7 & 6 & 5 \\ -2 & 1 & 3 \\ 7 & 3 & 7
        \end{bmatrix}
      \end{displaymath}
    \item On a
      \begin{displaymath}
        \mat{A} \mat{B}
        =
        \begin{bmatrix}
          3 & 0 \\ -1 & 2 \\ 1 & 1
        \end{bmatrix}
        \begin{bmatrix}
          4 & -1 \\ 0 & 2
        \end{bmatrix}
        =
        \begin{bmatrix}
          12 & -3 \\ -4 & 5 \\ 4 & 1
        \end{bmatrix}.
      \end{displaymath}
    \item On a
      \begin{align*}
        (2 \mat{D}^T - \mat{E}) \mat{A}
        &=
        \left(
          2
          \begin{bmatrix}
            1 & -1 & 3 \\ 5 & 0 & 2 \\ 2 & 1 & 4
          \end{bmatrix} -
          \begin{bmatrix}
            6 & 1 & 3 \\ -1 & 1 & 2 \\ 4 & 1 & 3
          \end{bmatrix}
        \right)
        \begin{bmatrix}
          3 & 0 \\ -1 & 2 \\ 1 & 1
        \end{bmatrix} \\
        &=
        \left(
          \begin{bmatrix}
            2 & -2 & 6 \\ 10 & 0 & 4 \\ 4 & 2 & 8
          \end{bmatrix} -
          \begin{bmatrix}
            6 & 1 & 3 \\ -1 & 1 & 2 \\ 4 & 1 & 3
          \end{bmatrix}
        \right)
        \begin{bmatrix}
          3 & 0 \\ -1 & 2 \\ 1 & 1
        \end{bmatrix} \\
        &=
        \begin{bmatrix}
          -4 & -3 & 3 \\ 11 & -1 & 2 \\ 0 & 1 & 5
        \end{bmatrix} -
        \begin{bmatrix}
          3 & 0 \\ -1 & 2 \\ 1 & 1
        \end{bmatrix} \\
        &=
        \begin{bmatrix}
          -6 & -3 \\ 36 & 0 \\ 4 & 7
        \end{bmatrix}.
      \end{align*}
    \item On a $(4 \mat{B}) \mat{C} + 2 \mat{B} = 2 \mat{B}(2\mat{C} +
      \mat{I})$. Or la somme entre parenthèses n'est pas définie
      puisque la matrice $\mat{C}$ n'est pas carrée.
    \item On a
      \begin{align*}
        (-\mat{AC})^T + 5 \mat{D}^T
        &=
        \left(
          -
          \begin{bmatrix}
            3 & 0 \\ -1 & 2 \\ 1 & 1
          \end{bmatrix}
          \begin{bmatrix}
            1 & 4 & 2 \\ 3 & 1 & 5
          \end{bmatrix}
        \right)^T + 5
        \begin{bmatrix}
          1 & 5 & 2 \\ -1 & 0 & 1 \\ 3 & 2 & 4
        \end{bmatrix}^T \\
        &=
        \left(
          -
          \begin{bmatrix}
            3 & 12 & 6 \\ 5 & -2 & 8 \\ 4 & 5 & 7
          \end{bmatrix}
        \right)^T +
        \begin{bmatrix}
          5 & -5 & 15 \\ 25 & 0 & 10 \\ 10 & 5 & 20
        \end{bmatrix} \\
        &=
        \begin{bmatrix}
          -3 & -5 & -4 \\ -12 & 2 & -5 \\ -6 & -8 & -7
        \end{bmatrix} +
        \begin{bmatrix}
          5 & -5 & 15 \\ 25 & 0 & 10 \\ 10 & 5 & 20
        \end{bmatrix} \\
        &=
        \begin{bmatrix}
          2 & -10 & 11 \\ 13 & 2 & 5 \\ 4 & -3 & 13
        \end{bmatrix}.
      \end{align*}
    \item On a
      \begin{align*}
        (\mat{BA}^T - 2 \mat{C})^T
        &=
        \left(
          \begin{bmatrix}
            4 & -1 \\ 0 & 2
          \end{bmatrix}
          \begin{bmatrix}
            3 & -1 & 1 \\ 0 & 2 & 1
          \end{bmatrix} -
          \begin{bmatrix}
            2 & 8 & 4 \\ 6 & 2 & 10
          \end{bmatrix}
        \right)^T \\
        &=
        \left(
          \begin{bmatrix}
            12 & -6 & 3 \\ 0 & 4 & 2
          \end{bmatrix} -
          \begin{bmatrix}
            2 & 8 & 4 \\ 6 & 2 & 10
          \end{bmatrix}
        \right)^T \\
        &=
        \begin{bmatrix}
          10 & -6 \\ -14 & 2 \\ -1 & -8
        \end{bmatrix}
      \end{align*}
    \item On a
      \begin{align*}
        \mat{C} \mat{C}^T
        &=
        \begin{bmatrix}
          1 & 4 & 2 \\ 3 & 1 & 5
        \end{bmatrix}
        \begin{bmatrix}
          1 & 3 \\ 4 & 1 \\ 2 & 5
        \end{bmatrix} =
        \begin{bmatrix}
          21 & 17 \\ 17 & 35
        \end{bmatrix} \\
        \intertext{et}
        \mat{A}^T \mat{A}
        &=
        \begin{bmatrix}
          3 & -1 & 1 \\ 0 & 2 & 1
        \end{bmatrix}
        \begin{bmatrix}
          3 & 0 \\ -1 & 2 \\ 1 & 1
        \end{bmatrix} =
        \begin{bmatrix}
          11 & -1 \\ -1 & 5
        \end{bmatrix}, \\
        \intertext{d'où}
        \mat{B}^T (\mat{CC}^T - \mat{A}^T \mat{A})
        &=
        \begin{bmatrix}
          4 & 0 \\ -1 & 2
        \end{bmatrix}
        \begin{bmatrix}
          10 & 18 \\ 18 & 30
        \end{bmatrix} =
        \begin{bmatrix}
          40 & 72 \\ 26 & 42
        \end{bmatrix}
      \end{align*}
    \item On a $\mat{D}^T \mat{E}^T - (\mat{ED})^T = (\mat{ED})^T -
      (\mat{ED})^T = \mat{0}_{3 \times 3}$.
    \item Pour calculer la trace, il suffit de connaître les éléments
      de la diagonale. Or l'élément $d_{ii}$ de $\mat{D}\mat{D}^T$ est
      la somme des carrés des éléments de la ligne $i$ de la matrice
      $\mat{D}$. Par conséquent, $\tr(\mat{D}\mat{D}^T) = (1 + 25 + 4)
      + (1 + 0 + 1) + (9 + 4 + 16) = 61$.
    \item Encore une fois, on se concentre seulement sur les éléments
      de la diagonale de $4 \mat{E}^T - \mat{D}$. La transposée ne
      joue donc aucun rôle, ici. Ainsi, $\tr(4 \mat{E}^T - \mat{D}) =
      (24 - 1) + (4 - 0) + (12 - 4) = 35$.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \raggedright
    \begin{inparaenum}
    \item $\begin{bmatrix} 7 & 6 & 5 \\ -2 & 1 & 3 \\ 7 & 3 & 7
      \end{bmatrix}$
    \item $\begin{bmatrix} 12 & -3 \\ -4 & 5 \\ 4 & 1 \end{bmatrix}$
    \item $\begin{bmatrix} -6 & -3 \\ 36 & 0 \\ 4 & 7 \end{bmatrix}$
    \item non défini
    \item $\begin{bmatrix} 2 & -10 & 11 \\ 13 & 2 & 5 \\ 4 & -3 & 13
      \end{bmatrix}$
    \item $\begin{bmatrix} 10 & -6 \\ -14 & 2 \\ -1 & -8
      \end{bmatrix}$
    \item $\begin{bmatrix} 40 & 72 \\ 26 & 42 \end{bmatrix}$
    \item $\begin{bmatrix} 0&0&0 \\ 0&0&0 \\ 0&0&0 \end{bmatrix}$
    \item 61
    \item 35
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Démontrer que si $\mat{A}$ et $\mat{B}$ sont deux matrices $n \times
  n$, alors $\tr(\mat{A} + \mat{B}) = \tr({\mat{A}}) +
  \tr({\mat{B}})$, où $\tr(\mat{A}) = \sum_{i=1}^n a_{ii}$.
  \begin{sol}
    Puisque $\tr(\mat{A}) = \sum_{i=1}^n a_{ii}$, alors
    \begin{align*}
      \tr({\mat{A}}) + \tr({\mat{B}})
      &= \sum_{i=1}^n a_{ii} + \sum_{i=1}^n b_{ii} \\
      &= \sum_{i=1}^n (a_{ii} + b_{ii}) \\
      &= \tr(\mat{A} + \mat{B}).
    \end{align*}
  \end{sol}
\end{exercice}

\begin{exercice}
  Une matrice $\mat{A}$ est dite \emph{symétrique} si $\mat{A}^T =
  \mat{A}$ et \emph{antisymétrique} si $\mat{A}^T = - \mat{A}$.
  Démontrer les énoncés suivants, étant donné une matrice carrée
  $\mat{A}$.
  \begin{enumerate}
  \item $\mat{AA}^T$ et $\mat{A}^T\mat{A}$ sont symétriques.
  \item $\mat{A} - \mat{A}^T$ est antisymétrique.
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item On a que $(\mat{A} \mat{A}^T)^T = (\mat{A}^T)^T \mat{A}^T =
      \mat{A} \mat{A}^T$, d'où $\mat{A} \mat{A}^T$ est symétrique. On
      procède de même pour le second résultat.
    \item On a que $(\mat{A} - \mat{A}^T)^T = \mat{A}^T - \mat{A} =
      -(\mat{A} - \mat{A}^T)$, d'où $\mat{A} - \mat{A}^T$ est
      antisymétrique.
    \end{enumerate}
  \end{sol}
\end{exercice}

\begin{exercice}
  Démontrer que si $\mat{A}^T \mat{A} = \mat{A}$, alors $\mat{A}$
  est symétrique et $\mat{A} = \mat{A}^2$. Une matrice qui satisfait
  cette dernière égalité est dite \emph{idempotente}.
  \begin{sol}
    Tout d'abord, $\mat{A}^T = (\mat{A}^T \mat{A})^T = \mat{A}^T
    \mat{A} = \mat{A}$, d'où $\mat{A}^T \mat{A}$ est symétrique. De
    plus, si $\mat{A}$ est symétrique, alors $\mat{A} = \mat{A}^T
    \mat{A} = \mat{A} \mat{A} = \mat{A}^2$. La matrice $\mat{A}$ est
    donc idempotente.
  \end{sol}
\end{exercice}

\begin{exercice}
  Lesquels des ensembles de vecteurs dans $\R^3$ suivants sont
  linéairement dépendants?
  \begin{enumerate}
  \item $( 4, -1,  2)$, $(-4, 10,  2)$
  \item $(-3,  0,  4)$, $( 5, -1,  2)$, $( 1,  1,  3)$
  \item $( 8, -1,  3)$, $( 4,  0,  1)$
  \item $(-2,  0,  1)$, $( 3,  2,  5)$, $( 6, -1,  1)$, $(7, 0, -2)$
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item Deux vecteurs de $\mathbb{R}^3$ sont nécessairement
      linéairement indépendants à moins que l'un ne soit un multiple
      de l'autre. Ce n'est pas le cas ici.
    \item Trois vecteurs sont linéairement dépendants si l'un est une
      combinaison linéaire des deux autres. Si c'est le cas, le
      déterminant de la matrice formée des coordonnées des vecteurs
      sera nul. Or, ici,
      \begin{displaymath}
        \begin{vmatrix}
          -3 & 5 & 1 \\ 0 & -1 & 1 \\ 4 & 2 & 3
        \end{vmatrix} = 39 \neq 0.
      \end{displaymath}
      Les vecteurs sont donc linéairement indépendants.
    \item Le second vecteur n'est pas un multiple du premier, donc les
      vecteurs sont linéairement indépendants.
    \item Un ensemble de quatre vecteurs de $\mathbb{R}^3$ est
      nécessairement linéairement dépendant.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    d) seulement
  \end{rep}
\end{exercice}

\begin{exercice}
  Soit $\mat{v}_1, \mat{v}_2, \mat{v}_3 \in \R^3$. Déterminer si
  les trois vecteurs se trouvent dans un plan.
  \begin{enumerate}
  \item $\mat{v}_1 = ( 2, -2,  0)$,
        $\mat{v}_2 = ( 6,  1,  4)$,
        $\mat{v}_3 = ( 2,  0, -4)$
  \item $\mat{v}_1 = (-6,  7,  2)$,
        $\mat{v}_2 = ( 3,  2,  4)$,
        $\mat{v}_3 = ( 4, -1,  2)$
  \end{enumerate}
  \begin{sol}
    Les trois vecteurs se trouvent dans un plan si seulement deux
    vecteurs sont linéairement indépendants (ceux-ci engendrent un
    plan dont fait alors partie le troisième).
    \begin{enumerate}
    \item Soit la matrice
      \begin{displaymath}
        \mat{A} =
        \begin{bmatrix}
          2 & 6 & 2 \\ -2 & 1 & 0 \\ 0 & 4 & -4
        \end{bmatrix}.
      \end{displaymath}
      En additionnant la première et la deuxième ligne, on obtient
      \begin{displaymath}
        \begin{bmatrix}
          2 & 6 & 2 \\ 0 & 7 & 2 \\ 0 & 4 & -4
        \end{bmatrix}.
      \end{displaymath}
      La troisième ligne n'étant pas un multiple de la deuxième, on
      cons\-tate que la seule solution du système d'équations homogène
      $\mat{A} \mat{x} = \mat{0}$ est la solution triviale. Par
      conséquent, les trois vecteurs sont linéairement indépendants et
      ne se trouvent pas dans un plan. On pourrait également vérifier
      que $\det(\mat{A}) \neq 0$.
    \item Soit la matrice
      \begin{displaymath}
        \mat{A} =
        \begin{bmatrix}
          -6 & 3 & 4 \\ 7 & 2 & -1 \\ 2 & 4 & 2
        \end{bmatrix}.
      \end{displaymath}
      À la suite d'opérations élémentaires sur les lignes, on obtient
      \begin{displaymath}
        \begin{bmatrix}
          -6 & 3 & 4 \\ 0 & 3 & 2 \\ 0 & 0 & 0
        \end{bmatrix}.
      \end{displaymath}
      Il n'y a donc que deux vecteurs linéairement indépendants
      formant un plan dans cet ensemble.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{inparaenum}
    \item non
    \item oui
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  \label{ex:notions:inverse_diagonale}
  Soit la matrice
  \begin{displaymath}
    \mat{A} =
    \begin{bmatrix}
      a_{11} &      0 & \cdots &      0 \\
           0 & a_{22} & \cdots &      0 \\
      \vdots & \vdots &        & \vdots \\
           0 &      0 & \cdots & a_{nn}
    \end{bmatrix},
  \end{displaymath}
  où $\prod_{i=1}^n a_{ii} \neq 0$. Démontrer que $\mat{A}$ est
  inversible et trouver son inverse.
  \begin{sol}
    On peut interpréter la condition $\prod_{i=1}^n a_{ii} \neq 0$
    comme le fait que le déterminant de la matrice est non nul, ou
    comme le fait qu'il n'y aucun zéro sur la diagonale et, par
    conséquent, aucune ligne de zéros dans la matrice. Dans un cas
    comme dans l'autre, cela signifie que l'inverse existe. En
    utilisant la technique consistant à transformer la matrice
    $[\mat{A}|\mat{I}]$ en $[\mat{I}|\mat{A}^{-1}]$, on voit
    immédiatement que
    \begin{displaymath}
      \mat{A} =
      \begin{bmatrix}
        a_{11}^{-1} &          0 & \cdots &      0 \\
                 0 & a_{22}^{-1} & \cdots &      0 \\
            \vdots &     \vdots &        & \vdots \\
                 0 &          0 & \cdots & a_{nn}^{-1}
      \end{bmatrix}.
    \end{displaymath}
  \end{sol}
\end{exercice}

\begin{exercice}
  Soit les matrices
  \begin{align*}
    \mat{A}
    &=
    \begin{bmatrix}
      3 & 4 & 1 \\ 2 & -7 & -1 \\ 8 & 1 & 5
    \end{bmatrix} &
    \mat{B}
    &=
    \begin{bmatrix}
      8 & 1 & 5 \\ 2 & -7 & -1 \\ 3 & 4 & 1
    \end{bmatrix} &
    \mat{C}
    &=
    \begin{bmatrix}
      3 & 4 & 1 \\ 2 & -7 & -1 \\ 2 & -7 & 3
    \end{bmatrix}.
  \end{align*}
  Trouver les matrices élémentaires $\mat{E}_1$, $\mat{E}_2$ et
  $\mat{E}_3$ satisfaisant les équations suivantes.
  \begin{enumerate}
    \begin{multicols}{4}
    \item $\mat{E}_1 \mat{A} = \mat{B}$
    \item $\mat{E}_2 \mat{B} = \mat{A}$
    \item $\mat{E}_3 \mat{A} = \mat{C}$
    \item $\mat{E}_4 \mat{C} = \mat{A}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    Une matrice élémentaire est le résultat d'une opération
    élémentaire sur la matrice identité.
    \begin{enumerate}
    \item On souhaite inverser les première et troisième ligne de la
      matrice $\mat{A}$. Par conséquent,
      \begin{displaymath}
        \mat{E}_1 =
        \begin{bmatrix}
          0 & 0 & 1 \\ 0 & 1 & 0 \\ 1 & 0 & 0
        \end{bmatrix}.
      \end{displaymath}
    \item Même chose que ci-dessus.
    \item La matrice $\mat{C}$ est obtenue à partir de la matrice
      $\mat{A}$ en additionnant $-2$ fois la première ligne à la
      troisième ligne. Par conséquent,
      \begin{displaymath}
        \mat{E}_3 =
        \begin{bmatrix}
          1 & 0 & 0 \\ 0 & 1 & 0 \\ -2 & 0 & 1
        \end{bmatrix}.
      \end{displaymath}
    \item De façon similaire, on obtient la matrice $\mat{A}$ en
      additionnant 2 fois la première ligne de la matrice $\mat{C}$ à
      la troisième ligne. On a donc
      \begin{displaymath}
        \mat{E}_4 =
        \begin{bmatrix}
          1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1
        \end{bmatrix}.
      \end{displaymath}
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{inparaenum}
    \item $\begin{bmatrix} 0&0&1 \\ 0&1&0 \\ 1&0&0 \end{bmatrix}$
    \item $\begin{bmatrix} 0&0&1 \\ 0&1&0 \\ 1&0&0 \end{bmatrix}$
    \item $\begin{bmatrix} 1&0&0 \\ 0&1&0 \\ -2&0&1 \end{bmatrix}$
    \item $\begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 2&0&1 \end{bmatrix}$
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  \label{ex:notions:inverse_par_op_elementaires}
  Utiliser la méthode des opérations élémentaires sur les lignes pour
  trouver l'inverse des matrices suivantes, si elle existe. Le cas
  échéant, vérifier votre réponse par multiplication de la matrice et
  de son inverse.
  \begin{enumerate}
    \begin{multicols}{3}
    \item $%
      \begin{bmatrix}
        3 & 4 & -1 \\ 1 & 0 & 3 \\ 2 & 5 & -4
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        -1 & 3 & -4 \\ 2 & 4 & 1 \\ -4 & 2 & -9
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        1 & 0 & 1 \\ 0 & 1 & 1 \\ 1 & 1 & 0
      \end{bmatrix}$
    \end{multicols}
    \begin{multicols}{3}
    \item $%
      \begin{bmatrix}
        2 & 6 & 6 \\ 2 & 7 & 6 \\ 2 & 7 & 7
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        1 & 0 & 1 \\ -1 & 1 & 1 \\ 0 & 1 & 0
      \end{bmatrix}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    Par des opérations élémentaire sur les lignes, on cherche à
    transformer la matrice $[\mat{A}|\mat{I}]$ en
    $[\mat{I}|\mat{A}^{-1}]$. Ci-dessous, $L_i$ identifie la ligne $i$
    d'une matrice, le symbole $\leftarrow$ signifie qu'une ligne est
    remplacée et le symbole $\leftrightarrow$ que deux lignes sont
    échangées.
    \begin{enumerate}
    \item
      \begin{multicols}{2}
        Matrice de départ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            3 & 4 & -1 & 1 & 0 & 0 \\
            1 & 0 &  3 & 0 & 1 & 0 \\
            2 & 5 & -4 & 0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_1 \leftrightarrow L_2$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 &  3 & 0 & 1 & 0 \\
            3 & 4 & -1 & 1 & 0 & 0 \\
            2 & 5 & -4 & 0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_2 \leftarrow -3 L_1 + L_2$ \\
        $L_3 \leftarrow -2 L_1 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 &   3 & 0 &  1 & 0 \\
            0 & 4 & -10 & 1 & -3 & 0 \\
            0 & 5 & -10 & 0 & -2 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow -L_2 + L_3$ \\
        $L_2 \leftrightarrow L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 &   3 &  0 &  1 & 0 \\
            0 & 1 &   0 & -1 &  1 & 1 \\
            0 & 4 & -10 &  1 & -3 & 0
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow -4 L_2 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 &   3 &  0 &  1 &  0 \\
            0 & 1 &   0 & -1 &  1 &  1 \\
            0 & 0 & -10 &  5 & -7 & -4
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow -L_3/10$ \\
        $L_1 \leftarrow -3 L_3 + L_1$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 & 0 &  \frac{3}{2} & -\frac{11}{10} & -\frac{6}{5} \\
            0 & 1 & 0 & -1 &  1 &  1 \\
            0 & 0 & 1 & -\frac{1}{2} & \frac{7}{10} & \frac{2}{5}
          \end{array}
        \right]
        $
      \end{multicols}
    \item
      \begin{multicols}{2}
        Matrice de départ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            -1 & 3 & -4 & 1 & 0 & 0 \\
             2 & 4 &  1 & 0 & 1 & 0 \\
            -4 & 2 & -9 & 0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_2 \leftarrow 2 L_1 + L_2$ \\
        $L_3 \leftarrow -4 L_1 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            -1 &   3 & -4 &  1 & 0 & 0 \\
             0 &  10 & -7 &  2 & 1 & 0 \\
             0 & -10 &  7 & -4 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow L_2 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            -1 &   3 & -4 &  1 & 0 & 0 \\
             0 &  10 & -7 &  2 & 1 & 0 \\
             0 &   0 &  0 & -2 & 1 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      L'inverse n'existe pas puisque l'on obtient une ligne de zéros
      du côté gauche de la matrice augmentée.
    \item
      \begin{multicols}{2}
        Matrice de départ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 & 1 & 1 & 0 & 0 \\
            0 & 1 & 1 & 0 & 1 & 0 \\
            1 & 1 & 0 & 0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow - L_1 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 &  1 &  1 & 0 & 0 \\
            0 & 1 &  1 &  0 & 1 & 0 \\
            0 & 1 & -1 & -1 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow - L_2 + L_3$ \\
        $L_3 \leftarrow - L_3/2$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 &  1 &  1 & 0 & 0 \\
            0 & 1 &  1 &  0 & 1 & 0 \\
            0 & 0 &  1 & \frac{1}{2} & \frac{1}{2} & -\frac{1}{2}
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_2 \leftarrow - L_3 + L_2$ \\
        $L_1 \leftarrow - L_3 + L_1$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 0 & 0 &  \frac{1}{2} & -\frac{1}{2} &  \frac{1}{2} \\
            0 & 1 & 0 & -\frac{1}{2} &  \frac{1}{2} &  \frac{1}{2} \\
            0 & 0 & 1 &  \frac{1}{2} &  \frac{1}{2} & -\frac{1}{2}
          \end{array}
        \right]
        $
      \end{multicols}
    \item
      \begin{multicols}{2}
        Matrice de départ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            2 & 6 & 6 & 1 & 0 & 0 \\
            2 & 7 & 6 & 0 & 1 & 0 \\
            2 & 7 & 7 & 0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_2 \leftarrow - L_1 + L_2$ \\
        $L_3 \leftarrow - L_1 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            2 & 6 & 6 &  1 & 0 & 0 \\
            0 & 1 & 0 & -1 & 1 & 0 \\
            0 & 1 & 1 & -1 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_1 \leftarrow L_1/2$ \\
        $L_3 \leftarrow - L_2 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 3 & 3 &  \frac{1}{2} &  0 & 0 \\
            0 & 1 & 0 &           -1 &  1 & 0 \\
            0 & 0 & 1 &            0 & -1 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_1 \leftarrow - 3 L_3 + L_1$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 3 & 0 &  \frac{1}{2} &  3 & -3 \\
            0 & 1 & 0 &           -1 &  1 &  0 \\
            0 & 0 & 1 &            0 & -1 &  1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_1 \leftarrow - 3 L_2 + L_1$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
            1 & 3 & 0 &  \frac{7}{2} &  0 & -3 \\
            0 & 1 & 0 &           -1 &  1 &  0 \\
            0 & 0 & 1 &            0 & -1 &  1
          \end{array}
        \right]
        $
      \end{multicols}
    \item
    \begin{multicols}{2}
        Matrice de départ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
             1 & 0 & 1 & 1 & 0 & 0 \\
            -1 & 1 & 1 & 0 & 1 & 0 \\
             0 & 1 & 0 & 0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_2 \leftrightarrow L_3$ \\
        $L_3 \leftarrow L_1 + L_3$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
             1 & 0 & 1 & 1 & 0 & 0 \\
             0 & 1 & 0 & 0 & 0 & 1 \\
             0 & 1 & 2 & 1 & 1 & 0
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow - L_2 + L_3$ \\
        $L_3 \leftarrow L_3/2$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
             1 & 0 & 1 & 1 & 0 & 0 \\
             0 & 1 & 0 & 0 & 0 & 1 \\
             0 & 0 & 1 & \frac{1}{2} &  \frac{1}{2} & -\frac{1}{2}
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_1 \leftarrow - L_3 + L_1$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrr|rrr}
             1 & 0 & 0 & \frac{1}{2} & -\frac{1}{2} &  \frac{1}{2} \\
             0 & 1 & 0 & 0 & 0 & 1 \\
             0 & 0 & 1 & \frac{1}{2} &  \frac{1}{2} & -\frac{1}{2}
          \end{array}
        \right]
        $
      \end{multicols}
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \raggedright
    \begin{inparaenum}
    \item $\begin{bmatrix}
        \frac{3}{2} & -\frac{11}{10} & -\frac{6}{5} \\
        -1 & 1 & 1 \\
        -\frac{1}{2} & \frac{7}{10} & \frac{2}{5}
      \end{bmatrix}$
     \item n'existe pas
     \item $\dfrac{1}{2} \begin{bmatrix} 1&-1&1 \\ -1&1&1 \\ 1&1&-1
       \end{bmatrix}$
     \item $\begin{bmatrix}
         \frac{7}{2} & 0 & -3 \\
         -1 & 1 & 0 \\
         0 & - 1 & 1
       \end{bmatrix}$
     \item $\dfrac{1}{2} \begin{bmatrix} 1&-1&1 \\ 0&0&2 \\ 1&1&-1
       \end{bmatrix}$
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Trouver l'inverse des matrices suivantes, où $k, k_1, \dots k_4$
  sont des cons\-tantes non nulles.
  \begin{multicols}{3}
    \begin{enumerate}
    \item $%
      \begin{bmatrix}
        k_1 & 0 & 0 & 0 \\
        0 & k_2 & 0 & 0 \\
        0 & 0 & k_3 & 0 \\
        0 & 0 & 0 & k_4
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        0 & 0 & 0 & k_1 \\
        0 & 0 & k_2 & 0 \\
        0 & k_3 & 0 & 0 \\
        k_4 & 0 & 0 & 0
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        k & 0 & 0 & 0 \\
        1 & k & 0 & 0 \\
        0 & 1 & k & 0 \\
        0 & 0 & 1 & k
      \end{bmatrix}$
    \end{enumerate}
  \end{multicols}
  \begin{sol}
    \begin{enumerate}
    \item Tel que démontré à l'\autoref{ex:notions:inverse_diagonale},
      l'inverse est
      \begin{displaymath}
        \begin{bmatrix}
          k_1^{-1} & 0 & 0 & 0 \\
          0 & k_2^{-1} & 0 & 0 \\
          0 & 0 & k_3^{-1} & 0 \\
          0 & 0 & 0 & k_4^{-1}
        \end{bmatrix}.
      \end{displaymath}
    \item Pour obtenir l'inverse de cette matrice par la méthode
      utilisée à l'\autoref{ex:notions:inverse_par_op_elementaires},
      il suffit d'échanger les lignes de bas en haut, puis de diviser
      celles-ci par $k_4$, $k_3$, $k_2$ et $k_1$, respectivement. On
      trouve alors que l'inverse est
      \begin{displaymath}
        \begin{bmatrix}
          0 & 0 & 0 & k_4^{-1} \\
          0 & 0 & k_3^{-1} & 0 \\
          0 & k_2^{-1} & 0 & 0 \\
          k_1^{-1} & 0 & 0 & 0
        \end{bmatrix}.
      \end{displaymath}
      \pagebreak[3]
    \item On utilise la méthode de l'\autoref{ex:notions:inverse_par_op_elementaires}.
      \setlength{\ocolumnsep}{\columnsep}
      \setlength{\columnsep}{-120pt}
      \begin{multicols}{2}
        Matrice de départ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrrr|rrrr}
            k & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
            1 & k & 0 & 0 & 0 & 1 & 0 & 0 \\
            0 & 1 & k & 0 & 0 & 0 & 1 & 0 \\
            0 & 0 & 1 & k & 0 & 0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_1 \leftarrow L_1/k$ \\
        $L_2 \leftarrow - L_1 + L_2$ \\
        $L_2 \leftarrow L_2/k$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrrr|rrrr}
            1 & 0 & 0 & 0 &  k^{-1} &     0 & 0 & 0 \\
            0 & 1 & 0 & 0 & -k^{-2} & k^{-1} & 0 & 0 \\
            0 & 1 & k & 0 &       0 &     0 & 1 & 0 \\
            0 & 0 & 1 & k &       0 &     0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_3 \leftarrow - L_2 + L_3$ \\
        $L_3 \leftarrow L_3/k$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrrr|rrrr}
            1 & 0 & 0 & 0 &  k^{-1} &      0 &      0 & 0 \\
            0 & 1 & 0 & 0 & -k^{-2} &  k^{-1} &     0 & 0 \\
            0 & 0 & 1 & 0 &  k^{-3} & -k^{-2} & k^{-1} & 0 \\
            0 & 0 & 1 & k &       0 &      0 & 0 & 1
          \end{array}
        \right]
        $
      \end{multicols}
      \begin{multicols}{2}
        $L_4 \leftarrow - L_3 + L_4$ \\
        $L_4 \leftarrow L_4/k$ \\
        \columnbreak
        $%
        \left[
          \begin{array}{rrrr|rrrr}
            1 & 0 & 0 & 0 &  k^{-1} &      0 &       0 & 0 \\
            0 & 1 & 0 & 0 & -k^{-2} &  k^{-1} &      0 & 0 \\
            0 & 0 & 1 & 0 &  k^{-3} & -k^{-2} &  k^{-1} & 0 \\
            0 & 0 & 0 & 1 & -k^{-4} &  k^{-3} & -k^{-2} & k^{-1}
          \end{array}
        \right]
        $
      \end{multicols}
      \setlength{\columnsep}{\ocolumnsep}
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \raggedright
    \begin{inparaenum}
    \item $%
      \begin{bmatrix}
        k_1^{-1} & 0 & 0 & 0 \\
        0 & k_2^{-1} & 0 & 0 \\
        0 & 0 & k_3^{-1} & 0 \\
        0 & 0 & 0 & k_4^{-1}
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        0 & 0 & 0 & k_1^{-1} \\
        0 & 0 & k_2^{-1} & 0 \\
        0 & k_3^{-1} & 0 & 0 \\
        k_4^{-1} & 0 & 0 & 0
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        k^{-1} & 0 & 0 & 0 \\
        -k^{-2} & k^{-1} & 0 & 0 \\
        k^{-3} & -k^{-2} & k^{-1} & 0 \\
        -k^{-4} & k^{-3} & -k^{-2} & k^{-1}
      \end{bmatrix}$
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Soit la matrice
  \begin{displaymath}
    \mat{A} =
    \begin{bmatrix}
      1 & 0 \\ -5 & 2
    \end{bmatrix}.
  \end{displaymath}
  \begin{enumerate}
  \item Trouver des matrices élémentaires $\mat{E}_1$ et $\mat{E}_2$
    tel que $\mat{E}_2 \mat{E}_1 \mat{A} = \mat{I}$.
  \item Écrire $\mat{A}^{-1}$ comme le produit de deux matrices
    élémentaires.
  \item Écrire $\mat{A}$ comme le produit de deux matrices
    élémentaires.
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item Les opérations élémentaires à effectuer pour transformer la
      matrice $\mat{A}$ en matrice identité sont, dans l'ordre:
      \begin{enumerate}[1.]
      \item additionner 5 fois la première ligne à la deuxième;
      \item multiplier la deuxième ligne par $\frac{1}{2}$.
      \end{enumerate}
      Les matrices élémentaires correspondantes sont
      \begin{displaymath}
        \mat{E}_1 =
        \begin{bmatrix} 1&0 \\ 5&1 \end{bmatrix} \quad
        \text{et} \quad
        \mat{E}_2 = \begin{bmatrix} 1&0 \\ 0&\frac{1}{2} \end{bmatrix}.
      \end{displaymath}
    \item De la partie a), on a que
      \begin{displaymath}
        \mat{A}^{-1} = \mat{E}_2 \mat{E}_1 =
        \begin{bmatrix} 1 & 0 \\ \frac{5}{2} & \frac{1}{2} \end{bmatrix}.
      \end{displaymath}
    \item Du théorème 6.7 des notes de cours, une matrice élémentaire
      est inversible et son inverse est aussi une matrice élémentaire.
      Par conséquent, on peut isoler $\mat{A}$ dans l'équation
      $\mat{E}_2 \mat{E}_1 \mat{A} = \mat{I}$ pour obtenir $\mat{A} =
      \mat{E}_1^{-1} \mat{E}_2^{-1}$. Or,
      \begin{displaymath}
        \mat{E}_1^{-1} =
        \begin{bmatrix} 1&0 \\ -5&1 \end{bmatrix} \quad
        \text{et} \quad
        \mat{E}_2^{-1} = \begin{bmatrix} 1&0 \\ 0&2 \end{bmatrix},
      \end{displaymath}
      d'où
      \begin{displaymath}
        \mat{A} =
        \begin{bmatrix} 1&0 \\ -5&1 \end{bmatrix}
        \begin{bmatrix} 1&0 \\  0&2 \end{bmatrix}.
      \end{displaymath}
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{enumerate}
    \item $\mat{E}_1 = \begin{bmatrix} 1&0 \\ 5&1 \end{bmatrix}$,
      $\mat{E}_2 = \begin{bmatrix} 1&0 \\ 0&\frac{1}{2} \end{bmatrix}$
    \end{enumerate}
  \end{rep}
\end{exercice}

\begin{exercice}
  Résoudre le système d'équations suivant par la méthode de la matrice
  inverse:
  \begin{displaymath}
    \begin{array}[t]{*{2}{r@{\;}c@{\;}}r@{\;=\;}r}
      x_1 &+& 2x_2 &+& x_3 & -1 \\
      x_1 &-&  x_2 &+& x_3 &  3 \\
      x_1 &+&  x_2 & &     &  4.
    \end{array}
  \end{displaymath}
  \begin{sol}
    On a le système d'équations linéaires $\mat{A} \mat{x} = \mat{b}$ avec
    \begin{displaymath}
      \mat{A} =
      \begin{bmatrix}
        1 & 2 & 1 \\ 1 & - 1 & 1 \\ 1 & 1 & 0
      \end{bmatrix},
      \quad
      \mat{b} =
      \begin{bmatrix}
        -1 \\ 3 \\ 4
      \end{bmatrix}.
    \end{displaymath}
    Par la même technique que les exercices précédents, on trouve
    \begin{displaymath}
      \mat{A}^{-1} = \frac{1}{3}
      \begin{bmatrix}
        -1 & 1 & 3 \\ 1 & -1 & 0 \\ 2 & 1 & -3
      \end{bmatrix}.
    \end{displaymath}
    Par conséquent,
    \begin{displaymath}
      \mat{x} = \mat{A}^{-1} \mat{b} =
      \frac{1}{3}
      \begin{bmatrix}
        16 \\ -4 \\ -11
      \end{bmatrix}.
    \end{displaymath}
  \end{sol}
  \begin{rep}
    $x_1 = \frac{16}{3}$, $x_2 = -\frac{4}{3}$, $x_3 = -\frac{11}{3}$
  \end{rep}
\end{exercice}

\begin{exercice}
  Soit la matrice et le vecteur
  \begin{align*}
    \mat{A}
    &=
    \begin{bmatrix}
      2 & 1 & 2 \\ 2 & 2 & -2 \\ 3 & 1 & 1
    \end{bmatrix} &
    \mat{x}
    &=
    \begin{bmatrix}
      x_1 \\ x_2 \\ x_3
    \end{bmatrix}.
  \end{align*}
  \begin{enumerate}
  \item Vérifier que l'équation $\mat{Ax} = \mat{x}$ peut s'écrire
    sous la forme $(\mat{I} - \mat{A}) \mat{x} = \mat{0}$ et utiliser
    cette formule pour résoudre $\mat{Ax} = \mat{x}$ pour $\mat{x}$.
  \item Résoudre $\mat{Ax} = 4 \mat{x}$.
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item On a $\mat{A}\mat{x} = \mat{x} \Leftrightarrow \mat{x} -
      \mat{A}{x} = \mat{0} \Leftrightarrow (\mat{I} - \mat{A}) \mat{x}
      = \mat{0}$. On veut par la suite résoudre ce système d'équations
      homogène, où
      \begin{displaymath}
        \mat{I} - \mat{A} =
        \begin{bmatrix}
          -1 & -1 & -2 \\ -2 & -1 & 2 \\ -3 & -1 & 0
        \end{bmatrix}.
      \end{displaymath}
      Or, on peut vérifier que le déterminant de cette matrice est non
      nul, ce qui signifie que le système d'équations n'admet que la
      solution triviale $x_1 = x_2 = x_3 = 0$. On verra au
      \autoref{chap:valeurspropres} que cela signifie que 1 n'est pas
      une valeur propre de la matrice $\mat{A}$.
    \item On procède comme ci-dessus en résolvant cette fois le
      système d'équations linéaires homogène $(4\mat{I} - \mat{A})
      \mat{x} = \mat{0}$. Or,
      \begin{displaymath}
        4 \mat{I} - \mat{A} =
        \begin{bmatrix}
          2 & -1 & -2 \\ -2 & 2 & 2 \\ -3 & -1 & 3
        \end{bmatrix}.
      \end{displaymath}
      Après quelques opérations élémentaires sur les lignes de cette
      matrice, on obtient
      \begin{displaymath}
        \begin{bmatrix}
          2 & -1 & -2 \\ 0 & 1 & 0 \\ 0 & 0 & 0
        \end{bmatrix}.
      \end{displaymath}
      Le système d'équations a donc une infinité de solutions. En
      posant $x_3 = t$, on a $x_2 = 0$ et $x_1 = t$. Autrement dit,
      tout vecteur de la forme
      \begin{displaymath}
        \begin{bmatrix}
          t & 0 & t
        \end{bmatrix}
      \end{displaymath}
      est une solution de l'équation $\mat{A} \mat{x} = 4 \mat{x}$.
      Encore une fois, on verra au \autoref{chap:valeurspropres}
      que 4 est une valeur propre de la matrice $\mat{A}$ et que $(t,
      0, t)$ est un vecteur propre correspondant.
    \end{enumerate}
  \end{sol}
\end{exercice}

\begin{exercice}
  Sans faire aucun calcul, déterminer si les systèmes d'équations
  homogènes ci-dessous admettent une solution autre que la solution
  triviale, puis déterminer si la matrice des coefficients est
  inversible.
  \begin{multicols}{2}
    \begin{enumerate}
    \item $%
      \begin{array}[t]{*{3}{r@{\;}c@{\;}}r@{\;=\;}r}
        2x_1 &-&   x_2 &-&  3x_3 &+&   x_4 & 0 \\
             & &  5x_2 &+&  4x_3 &+&  3x_4 & 0 \\
             & &       & &   x_3 &+&  2x_4 & 0 \\
             & &       & &       & &  3x_4 & 0
      \end{array}$
    \item $%
      \begin{array}[t]{*{3}{r@{\;}c@{\;}}r@{\;=\;}r}
        5x_1 &-&   x_2 &+&  4x_3 &+&   x_4 & 0 \\
             & &       & &  2x_3 &-&   x_4 & 0 \\
             & &       & &   x_3 &+&   x_4 & 0 \\
             & &       & &       & &  7x_4 & 0
      \end{array}$
    \end{enumerate}
  \end{multicols}
  \begin{sol}
    Tel que vu au théorème 6.13 des notes de cours, les concepts
    d'inversibilité et de solution d'un système d'équations linéaires
    homogène sont liés: une matrice carrée $\mat{A}$ est inversible si
    et seulement si $\mat{A} \mat{x} = \mat{0}$ n'admet que la
    solution triviale.
    \begin{enumerate}
    \item Les quatre équations sont linéairement indépendantes, donc
      la matrice des coefficients est inversible et la seule solution
      du système est la solution triviale.
    \item Puisque que le coefficient de $x_2$ est 0 dans la seconde
      équation, les équations sont linéairement dépendantes, d'où la
      matrice des coefficients est singulière et il existe une
      infinité de solution pour le système d'équations homogène.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{inparaenum}
    \item solution triviale seulement, matrice inversible
    \item infinité de solutions, matrice singulière
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Par simple inspection visuelle de la matrice
  \begin{displaymath}
    \mat{A} =
    \begin{bmatrix}
      -2 &  8 &  1 &   4 \\
       3 &  2 &  5 &   1 \\
       1 & 10 &  6 &   5 \\
       4 & -6 &  4 &  -3
    \end{bmatrix},
  \end{displaymath}
  expliquer pourquoi $\det(\mat{A}) = 0$.
  \begin{sol}
    On voit que la troisième ligne de la matrice est la somme des deux
    premières. Les lignes n'étant pas linéairement indépendantes, le
    déterminant est nul.
  \end{sol}
\end{exercice}

\begin{exercice}
  Déterminer si les matrices suivantes sont inversibles.
  \begin{enumerate}
    \begin{multicols}{2}
    \item $%
      \begin{bmatrix}
        1 & 0 & -1 \\ 9 & -1 & 4 \\ 9 & 9 & -1
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        4 & 2 & 8 \\ -2 & 1 & -4 \\ 3 & 1 & 6
      \end{bmatrix}$
    \end{multicols}
    \begin{multicols}{2}
    \item $%
      \begin{bmatrix}
        \sqrt{2} & -\sqrt{7} & 0 \\
        3\sqrt{2} & -3 \sqrt{7} & 0 \\
        5 & -9 & 0
      \end{bmatrix}$
    \item $%
      \begin{bmatrix}
        -3 & 0 & 1 \\ 5 & 0 & 6 \\ 8 & 0 & 3
      \end{bmatrix}$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item Les lignes (et les colonnes) sont linéairement
      indépendantes, donc la matrice est inversible.
    \item La troisième colonne est un multiple de la première. Par
      conséquent, les colonnes ne sont pas linéairement indépendantes
      et la matrice est singulière.
    \item Le déterminant est clairement nul, donc la matrice est
      singulière.
    \item Idem.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{inparaenum}
    \item oui
    \item non
    \item non
    \item non
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Soit $\mat{A}$ une matrice $3 \times 3$ dont $\det(\mat{A}) = -7$.
  Trouver les déterminants suivants.
  \begin{enumerate}
    \begin{multicols}{4}
    \item $\det(3 \mat{A})$
    \item $\det(\mat{A}^{-1})$
    \item $\det(2 \mat{A}^{-1})$
    \item $\det((2 \mat{A})^{-1})$
    \end{multicols}
  \end{enumerate}
  \begin{sol}
    On utilise les propriétés du déterminant énoncées dans le théorème
    6.11 des notes de cours.
    \begin{enumerate}
    \item $\det(3 \mat{A}) = 3^3 \det(\mat{A}) = -189$
    \item $\det(\mat{A}^{-1}) = 1/\det(\mat{A}) = -\frac{1}{7}$
    \item $\det(2 \mat{A}^{-1}) = 2^3/\det(\mat{A}) = -\frac{8}{7}$
    \item $\det((2 \mat{A})^{-1}) = 2^{-3}/\det(\mat{A}) = -\frac{1}{56}$
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{inparaenum}
    \item $-189$
    \item $-\frac{1}{7}$
    \item $-\frac{8}{7}$
    \item $-\frac{1}{56}$
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Pour quelle(s) valeur(s) de $k$ les matrices ci-dessous ne sont
  pas inversibles?
  \begin{enumerate}
  \item $%
    \begin{bmatrix}
      k-3 & -2 \\ -2 & k-2
    \end{bmatrix}$
  \item $%
    \begin{bmatrix}
      1 & 2 & 4 \\ 3 & 1 & 6 \\ k & 3 & 2
    \end{bmatrix}$
  \end{enumerate}
  \begin{sol}
    Une matrice n'est pas inversible si son déterminant est nul.
    \begin{enumerate}
    \item Le déterminant de la matrice est $k^2 - 5k + 2$, donc la
      matrice est singulière lorsque $k = (5 \pm \sqrt{17})/2$.
    \item Le déterminant de la matrice est $8k + 8$, donc la
      matrice est singulière lorsque $k = -1$.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{inparaenum}
    \item $(5 \pm \sqrt{17})/2$
    \item $-1$
    \end{inparaenum}
  \end{rep}
\end{exercice}

\begin{exercice}
  Soit
  \begin{displaymath}
    \mat{A} =
    \begin{bmatrix}
      4 & -1 &  1 &  6 \\
      0 &  0 & -3 &  3 \\
      4 &  1 &  0 & 14 \\
      4 &  1 &  3 &  2
    \end{bmatrix}.
  \end{displaymath}
  Trouver les valeurs suivantes.
  \begin{enumerate}
  \item $M_{13}$ et $C_{13}$
  \item $M_{23}$ et $C_{23}$
  \item $M_{22}$ et $C_{22}$
  \item $M_{21}$ et $C_{21}$
  \item $\det(\mat{A})$
  \end{enumerate}
  \begin{sol}
    \begin{enumerate}
    \item On a
      \begin{displaymath}
        M_{13}
        =
        \begin{vmatrix}
          0 &  0 &  3 \\
          4 &  1 & 14 \\
          4 &  1 &  2
        \end{vmatrix}
        = 0,
      \end{displaymath}
      donc $C_{13} = 0$.
    \item On a
      \begin{displaymath}
        M_{23}
        =
        \begin{vmatrix}
          4 & -1 &  6 \\
          4 &  1 & 14 \\
          4 &  1 &  2
        \end{vmatrix}
        = 4(-12) - 4(-8) + 4(-20) \\
        = -96
      \end{displaymath}
      et $C_{23} = (-1)^5 (-96) = 96$.
    \item On a
      \begin{displaymath}
        M_{22}
        =
        \begin{vmatrix}
          4 &  1 &  6 \\
          4 &  0 & 14 \\
          4 &  3 &  2
        \end{vmatrix}
        = 4(-42) - 4(-16) + 4(14) \\
        = -48
      \end{displaymath}
      et $C_{22} = (-1)^4 (-48) = -48$.
    \item On a
      \begin{displaymath}
        M_{21}
        =
        \begin{vmatrix}
          -1 &  1 &  6 \\
           1 &  0 & 14 \\
           1 &  3 &  2
        \end{vmatrix}
        = -(-12 ) - 3(-20)
        = 72
      \end{displaymath}
      et $C_{21} = (-1)^3 (72) = -72$.
    \item En développant par la deuxième ligne, on a $\det(\mat{A}) =
      -3 C_{23} + 3 C_{24}$. Or, de ce qui précède, $C_{23} = 96$ et
      $C_{24} = M_{24} = 24$. Par conséquent, $\det(\mat{A}) = -216$.
    \end{enumerate}
  \end{sol}
  \begin{rep}
    \begin{enumerate}
    \item $M_{13} =   0$, $C_{13} =   0$
    \item $M_{23} = -96$, $C_{23} =  96$
    \item $M_{22} = -48$, $C_{22} = -48$
    \item $M_{21} =  72$, $C_{21} = -72$
    \item $-216$
    \end{enumerate}
  \end{rep}
\end{exercice}

\Closesolutionfile{reponses}
\Closesolutionfile{solutions}

\input{reponses-notions_fondamentales}

%%% Local Variables:
%%% mode: latex
%%% TeX-engine: xetex
%%% TeX-master: "methodes-numeriques-en-actuariat_algebre-lineaire.tex"
%%% coding: utf-8
%%% End:
